# Generated by Django 4.1.3 on 2023-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UBR_MDP_Table',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Year', models.PositiveIntegerField()),
                ('Month', models.CharField(max_length=500)),
                ('Circle', models.CharField(max_length=500)),
                ('Project', models.CharField(max_length=500)),
                ('Partner', models.CharField(max_length=500)),
                ('Done_Count', models.IntegerField(blank=True, null=True)),
                ('Projected_Count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
