# Generated by Django 4.1.3 on 2024-01-30 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0002_soft_at_huawei_rejected_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_AT_ZTE_Rejected_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Circle', models.CharField(max_length=500)),
                ('OEM', models.CharField(max_length=500)),
                ('TSP', models.CharField(max_length=500)),
                ('Site_ID', models.CharField(max_length=500)),
                ('No_of_Cell', models.CharField(max_length=500)),
                ('Cell_ID_Parent', models.CharField(max_length=500)),
                ('Cell_ID_New', models.CharField(max_length=500)),
                ('Technology', models.CharField(max_length=500)),
                ('Other_Tech_Info_Band', models.CharField(max_length=500)),
                ('Integration_Date', models.DateField(null=True)),
                ('Activity_Type', models.CharField(max_length=500)),
                ('OSS', models.CharField(max_length=500)),
                ('BSC', models.CharField(max_length=500)),
                ('Offer_Reoffer', models.CharField(max_length=500)),
                ('Offer_Reoffer_date', models.DateField(null=True)),
                ('AT_Type_Physical_AT_Soft_AT', models.CharField(max_length=500)),
                ('Cascaded_Remarks', models.CharField(max_length=500)),
                ('LAC', models.CharField(max_length=500)),
                ('TAC', models.CharField(max_length=500)),
                ('SiteID_MEID', models.CharField(max_length=500)),
                ('RET_Configuration_Remarks_Cell_Name', models.CharField(max_length=500)),
                ('Toco_Type_Shared_Anchor', models.CharField(max_length=500)),
                ('LAST_REJECTION_REMARKS', models.CharField(max_length=500)),
                ('DPR_Cell_Name', models.CharField(max_length=500)),
                ('Media', models.CharField(max_length=500)),
                ('Duplex', models.CharField(max_length=500)),
                ('Detected_Speed_Duplex', models.CharField(max_length=500)),
                ('M_plane', models.CharField(max_length=500)),
                ('Sync_Status', models.CharField(max_length=500)),
                ('User_Plane_IP', models.CharField(max_length=500)),
                ('TAC_ID', models.CharField(max_length=500)),
                ('CIRCUITID', models.CharField(max_length=500)),
                ('Date_Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
