# Generated by Django 4.1.3 on 2024-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0003_soft_at_zte_rejected_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_AT_ERI_Rejected_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AOP', models.CharField(max_length=500)),
                ('Circle', models.CharField(max_length=500)),
                ('OEM', models.CharField(max_length=500)),
                ('Offered_AT_Type', models.CharField(max_length=500)),
                ('Physical_Site_Id', models.CharField(max_length=500)),
                ('Site_ID', models.CharField(max_length=500)),
                ('Technology', models.CharField(max_length=500)),
                ('Layers_Other_Tech_Info', models.CharField(max_length=500)),
                ('Activity_Name', models.CharField(max_length=500)),
                ('RET_Configuration_Cell_Name', models.CharField(max_length=500)),
                ('RET_Configured_on_Layer', models.CharField(max_length=500)),
                ('Parent_Cell_Name_In_Case_Of_Twin_Beam', models.CharField(max_length=500)),
                ('Cell_Name_New', models.CharField(max_length=500)),
                ('MO_Name', models.CharField(max_length=500)),
                ('Node_IP', models.CharField(max_length=500)),
                ('OSS_Name_IP', models.CharField(max_length=500)),
                ('BSC_In_Case_Of_NT_2G', models.CharField(max_length=500)),
                ('OSS_ENM_For_BSC_In_Case_Of_NT_2G', models.CharField(max_length=500)),
                ('TAC_Name', models.CharField(max_length=500)),
                ('Cells_Configuration', models.CharField(max_length=500)),
                ('Scenario_In_Case_Of_Swap', models.CharField(max_length=500)),
                ('Hardware_RRU', models.CharField(max_length=500)),
                ('Hardware_BBU', models.CharField(max_length=500)),
                ('Antenna', models.CharField(max_length=500)),
                ('CPRI', models.CharField(max_length=500)),
                ('On_Air_Date', models.DateField(null=True)),
                ('SW_Version', models.CharField(max_length=500)),
                ('Sync_status_GPS_clock_NTP', models.CharField(max_length=500)),
                ('AT_Offering_Date', models.DateField(null=True)),
                ('MIMO_Power_configuration', models.CharField(max_length=500)),
                ('Media_Type', models.CharField(max_length=500)),
                ('Link_id', models.CharField(max_length=500)),
                ('Project_remarks', models.CharField(max_length=500)),
            ],
        ),
    ]
