# Generated by Django 4.1.3 on 2024-01-30 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0004_soft_at_eri_rejected_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_eri_rejected_table',
            name='Hardware_Made_OEM',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
