# Generated by Django 4.1.3 on 2024-01-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0005_soft_at_eri_rejected_table_hardware_made_oem'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_nokia_rejected_table',
            name='Cell_ID_2G',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_nokia_rejected_table',
            name='LNCEL_ID_PCI',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
