# Generated by Django 4.1.3 on 2024-01-31 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0006_soft_at_nokia_rejected_table_cell_id_2g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_eri_rejected_table',
            name='AT_Remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_eri_rejected_table',
            name='AT_STATUS',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_eri_rejected_table',
            name='Date_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='soft_at_zte_rejected_table',
            name='AT_Remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_zte_rejected_table',
            name='AT_STATUS',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
