# Generated by Django 4.1.3 on 2024-02-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0007_soft_at_eri_rejected_table_at_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks_To_Responsible_to_Manager_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('Responsible_Mail', models.EmailField(max_length=254, unique=True)),
                ('Managers', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
