# Generated by Django 4.1.3 on 2024-02-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0008_remarks_to_responsible_to_manager_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible_Person_Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsible_person_mail', models.EmailField(max_length=254)),
                ('Remarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soft_AT_Rejected.remarks')),
            ],
        ),
        migrations.DeleteModel(
            name='Remarks_To_Responsible_to_Manager_Mapping',
        ),
        migrations.AddField(
            model_name='managers',
            name='Respomsible_Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soft_AT_Rejected.responsible_person_mail'),
        ),
    ]
