# Generated by Django 4.1.3 on 2024-02-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0009_managers_remarks_responsible_person_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soft_at_eri_rejected_table',
            name='Hardware_Made_OEM',
        ),
    ]
