# Generated by Django 4.1.3 on 2024-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0010_remove_soft_at_eri_rejected_table_hardware_made_oem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centeral_Responsible_Spoc_Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=500, null=True)),
                ('Circle', models.CharField(max_length=254, null=True)),
                ('Central_Soft_At_Spoc_Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Central_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=500, null=True)),
                ('Circle', models.CharField(max_length=254, null=True)),
                ('Central_Management_Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Circle_PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=500, null=True)),
                ('Circle', models.CharField(max_length=254, null=True)),
                ('Circle_PM_Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Circle_Responsible_Spoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=500, null=True)),
                ('Circle', models.CharField(max_length=254, null=True)),
                ('Circle_Soft_At_Spoc_Mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rejection_Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=500, null=True)),
                ('Alarm_Bucket', models.CharField(max_length=500, null=True)),
                ('Rejection_Remark', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('Final_Responsibility', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='responsible_person_mail',
            name='Remarks',
        ),
        migrations.DeleteModel(
            name='Managers',
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
        migrations.DeleteModel(
            name='Responsible_Person_Mail',
        ),
    ]
