# Generated by Django 4.1.3 on 2024-02-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0011_centeral_responsible_spoc_mail_central_management_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soft_at_samsung_rejected_table',
            old_name='Kolkata_GPL_Type',
            new_name='GPL_Type',
        ),
    ]
