# Generated by Django 4.1.3 on 2024-02-20 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0012_rename_kolkata_gpl_type_soft_at_samsung_rejected_table_gpl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_AT_Rejection_Mail_Saved_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(max_length=500)),
                ('Date_Time', models.DateTimeField(default=datetime.datetime(2024, 2, 20, 7, 5, 55, 23606, tzinfo=datetime.timezone.utc))),
                ('Sender_Mail', models.EmailField(max_length=254)),
                ('Saved_Status', models.BooleanField(default=False)),
                ('Error_Status', models.CharField(max_length=500)),
            ],
        ),
    ]
