# Generated by Django 4.1.3 on 2024-02-20 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0013_soft_at_rejection_mail_saved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_at_rejection_mail_saved_status',
            name='Date_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
