# Generated by Django 4.1.3 on 2024-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0014_alter_soft_at_rejection_mail_saved_status_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejection_remarks',
            name='Rejection_Remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
