# Generated by Django 4.1.3 on 2024-02-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0018_alter_rejection_remarks_tesiing_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejection_remarks',
            name='Tesiing_Array',
        ),
    ]
