# Generated by Django 4.1.3 on 2024-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0019_remove_rejection_remarks_tesiing_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_accepted_rejected_table',
            name='CIRCLE_SPOC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_eri_rejected_table',
            name='CIRCLE_SPOC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_huawei_rejected_table',
            name='CIRCLE_SPOC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_nokia_rejected_table',
            name='CIRCLE_SPOC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_samsung_rejected_table',
            name='CIRCLE_SPOC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_zte_rejected_table',
            name='CIRCLE_SPOC',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
