# Generated by Django 4.1.3 on 2024-02-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0020_soft_at_accepted_rejected_table_circle_spoc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soft_at_accepted_rejected_table',
            old_name='CIRCLE_SPOC',
            new_name='CENTRAL_SPOC',
        ),
        migrations.RenameField(
            model_name='soft_at_eri_rejected_table',
            old_name='CIRCLE_SPOC',
            new_name='CENTRAL_SPOC',
        ),
        migrations.RenameField(
            model_name='soft_at_huawei_rejected_table',
            old_name='CIRCLE_SPOC',
            new_name='CENTRAL_SPOC',
        ),
        migrations.RenameField(
            model_name='soft_at_nokia_rejected_table',
            old_name='CIRCLE_SPOC',
            new_name='CENTRAL_SPOC',
        ),
        migrations.RenameField(
            model_name='soft_at_samsung_rejected_table',
            old_name='CIRCLE_SPOC',
            new_name='CENTRAL_SPOC',
        ),
        migrations.RenameField(
            model_name='soft_at_zte_rejected_table',
            old_name='CIRCLE_SPOC',
            new_name='CENTRAL_SPOC',
        ),
    ]
