# Generated by Django 4.1.3 on 2024-02-26 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0021_rename_circle_spoc_soft_at_accepted_rejected_table_central_spoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centeral_responsible_spoc_mail',
            name='prime_central_spocs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, default=[], size=15),
            preserve_default=False,
        ),
    ]
