# Generated by Django 4.1.3 on 2024-02-26 06:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0022_centeral_responsible_spoc_mail_prime_central_spocs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centeral_responsible_spoc_mail',
            name='prime_central_spocs',
        ),
        migrations.AddField(
            model_name='centeral_responsible_spoc_mail',
            name='Central_Soft_At_Prime_Spoc_Mail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=[], size=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centeral_responsible_spoc_mail',
            name='Central_Soft_At_Spoc_Mail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, size=15),
        ),
    ]
