# Generated by Django 4.1.3 on 2024-02-27 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Rejected', '0023_remove_centeral_responsible_spoc_mail_prime_central_spocs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='central_management',
            name='Central_Management_Mail',
        ),
        migrations.AddField(
            model_name='central_management',
            name='Central_Management_Mails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=[], size=15),
            preserve_default=False,
        ),
    ]
