from celery import shared_task
import datetime
from .models import Soft_At_Table


def update_key_with_current_date(key):
    # Split the key at "__" to isolate the date at the end
    key_parts = key.rsplit("__", 1)
    
    # Get the current date in the same format
    current_date = datetime.datetime.now().strftime("%Y-%m-%d")
    
    # Replace the old date with the current date and return the updated key
    updated_key = f"{key_parts[0]}__{current_date}"
    return updated_key

@shared_task
def create_next_day_records():
    current_date=datetime.datetime.now()
    previous_date=current_date-datetime.timedelta(days=1)
    print(current_date,previous_date)

    objs=Soft_At_Table.objects.filter(upload_date=previous_date) # just removed the .exclude(soft_at_status='Accepted') for testing purpose only
   
    print(len(objs),objs)
    for obj in objs:
        unique_key = update_key_with_current_date(obj.unique_key)
        if obj.soft_at_status == 'Rejected':
            new_record = Soft_At_Table.objects.create(
                upload_date=datetime.datetime.now().date(),
                unique_key=unique_key,  # Copy fields as required
                combination=obj.combination,
                IntegrationData=obj.IntegrationData,
                spoc_name=obj.spoc_name,
                offering_type=obj.offering_type,
                first_offering_date=obj.first_offering_date,
                soft_at_status='Pending',  # Change the status to 'pending'
                offering_date=obj.offering_date,
                acceptance_rejection_date=obj.acceptance_rejection_date,
                alarm_bucket=obj.alarm_bucket,
                alarm_details=obj.alarm_details,
                final_responsibility=obj.final_responsibility,
                workable_non_workable=obj.workable_non_workable,
                ubr_ms2_status=obj.ubr_ms2_status,
                ubr_link_id=obj.ubr_link_id,
                twamp_status=obj.twamp_status,
                status_check_date=obj.status_check_date,
                ageing_in_days=obj.ageing_in_days,
                actual_ageing=obj.actual_ageing,
                toco_partner=obj.toco_partner,
                support_required_ubr_team=obj.support_required_ubr_team,
                support_required_circle_team=obj.support_required_circle_team,
                support_required_noc_team=obj.support_required_noc_team,
                category=obj.category,
                problem_statement=obj.problem_statement,
                final_remarks=obj.final_remarks,
                ms1=obj.ms1,
                status_updated_by='auto_system', 
                 
                # integration data
                OEM=obj.OEM,
                Integration_Date=obj.Integration_Date,
                CIRCLE=obj.CIRCLE,
                Activity_Name=obj.Activity_Name,
                Site_ID=obj.Site_ID,
                MO_NAME=obj.MO_NAME,
                LNBTS_ID=obj.LNBTS_ID,
                Technology_SIWA=obj.Technology_SIWA,
                OSS_Details=obj.OSS_Details,
                Cell_ID=obj.Cell_ID,
                CELL_COUNT=obj.CELL_COUNT,
                TRX_Count=obj.TRX_Count,
                PRE_ALARM=obj.PRE_ALARM,
                GPS_IP_CLK=obj.GPS_IP_CLK,
                RET=obj.RET,
                POST_VSWR=obj.POST_VSWR,
                POST_Alarms=obj.POST_Alarms,
                Activity_Mode=obj.Activity_Mode,
                CELL_STATUS=obj.CELL_STATUS,
                CTR_STATUS=obj.CTR_STATUS,
                Integration_Remark=obj.Integration_Remark,
                T2T4R=obj.T2T4R,
                BBU_TYPE=obj.BBU_TYPE,
                BB_CARD=obj.BB_CARD,
                RRU_Type=obj.RRU_Type,
                Media_Status=obj.Media_Status,
                Mplane_IP=obj.Mplane_IP,
                SCF_PREPARED_BY=obj.SCF_PREPARED_BY,
                SITE_INTEGRATE_BY=obj.SITE_INTEGRATE_BY,
                Site_Status=obj.Site_Status,
                External_Alarm_Confirmation=obj.External_Alarm_Confirmation,
                SOFT_AT_STATUS=obj.SOFT_AT_STATUS,
                LICENCE_Status=obj.LICENCE_Status,
                ESN_NO=obj.ESN_NO,
                Responsibility_for_alarm_clearance=obj.Responsibility_for_alarm_clearance,
                TAC=obj.TAC,
                PCI_TDD_20=obj.PCI_TDD_20,
                PCI_TDD_10_20=obj.PCI_TDD_10_20,
                PCI_FDD_2100=obj.PCI_FDD_2100,
                PCI_FDD_1800=obj.PCI_FDD_1800,
                PCI_L900=obj.PCI_L900,
                PCI_5G=obj.PCI_5G,
                RSI_TDD_20=obj.RSI_TDD_20,
                RSI_TDD_10_20=obj.RSI_TDD_10_20,
                RSI_FDD_2100=obj.RSI_FDD_2100,
                RSI_FDD_1800=obj.RSI_FDD_1800,
                RSI_L900=obj.RSI_L900,
                RSI_5G=obj.RSI_5G,
                GPL=obj.GPL,
                Pre_Post_Check=obj.Pre_Post_Check,
                Activity_Type_SIWA=obj.Activity_Type_SIWA,
                Band_SIWA=obj.Band_SIWA,
                BSC_NAME=obj.BSC_NAME,
                BCF=obj.BCF,    
                


            )
        elif obj.soft_at_status == 'Accepted':
            new_record = Soft_At_Table.objects.create(
                upload_date=datetime.datetime.now().date(),
                unique_key=unique_key,  # Copy fields as required
                combination=obj.combination,
                IntegrationData=obj.IntegrationData,
                spoc_name=obj.spoc_name,
                offering_type=obj.offering_type,
                first_offering_date=obj.first_offering_date,
                soft_at_status= obj.soft_at_status,  # Change the status to 'pending'
                offering_date=obj.offering_date,
                acceptance_rejection_date=obj.acceptance_rejection_date,
                alarm_bucket=obj.alarm_bucket,
                alarm_details=obj.alarm_details,
                final_responsibility=obj.final_responsibility,
                workable_non_workable=obj.workable_non_workable,
                ubr_ms2_status=obj.ubr_ms2_status,
                ubr_link_id=obj.ubr_link_id,
                twamp_status=obj.twamp_status,
                status_check_date=obj.status_check_date,
                ageing_in_days=obj.ageing_in_days,
                actual_ageing=obj.actual_ageing,
                toco_partner=obj.toco_partner,
                support_required_ubr_team=obj.support_required_ubr_team,
                support_required_circle_team=obj.support_required_circle_team,
                support_required_noc_team=obj.support_required_noc_team,
                # support_required_sw_team=obj.support_required_sw_team,
                category=obj.category,
                # sub_category=obj.sub_category,
                problem_statement=obj.problem_statement,
                final_remarks=obj.final_remarks,
                ms1=obj.ms1,
                status_updated_by='auto_system', 
                soft_delete = obj.soft_delete,
                # integration data
                OEM=obj.OEM,
                Integration_Date=obj.Integration_Date,
                CIRCLE=obj.CIRCLE,
                Activity_Name=obj.Activity_Name,
                Site_ID=obj.Site_ID,
                MO_NAME=obj.MO_NAME,
                LNBTS_ID=obj.LNBTS_ID,
                Technology_SIWA=obj.Technology_SIWA,
                OSS_Details=obj.OSS_Details,
                Cell_ID=obj.Cell_ID,
                CELL_COUNT=obj.CELL_COUNT,
                TRX_Count=obj.TRX_Count,
                PRE_ALARM=obj.PRE_ALARM,
                GPS_IP_CLK=obj.GPS_IP_CLK,
                RET=obj.RET,
                POST_VSWR=obj.POST_VSWR,
                POST_Alarms=obj.POST_Alarms,
                Activity_Mode=obj.Activity_Mode,
                CELL_STATUS=obj.CELL_STATUS,
                CTR_STATUS=obj.CTR_STATUS,
                Integration_Remark=obj.Integration_Remark,
                T2T4R=obj.T2T4R,
                BBU_TYPE=obj.BBU_TYPE,
                BB_CARD=obj.BB_CARD,
                RRU_Type=obj.RRU_Type,
                Media_Status=obj.Media_Status,
                Mplane_IP=obj.Mplane_IP,
                SCF_PREPARED_BY=obj.SCF_PREPARED_BY,
                SITE_INTEGRATE_BY=obj.SITE_INTEGRATE_BY,
                Site_Status=obj.Site_Status,
                External_Alarm_Confirmation=obj.External_Alarm_Confirmation,
                SOFT_AT_STATUS=obj.SOFT_AT_STATUS,
                LICENCE_Status=obj.LICENCE_Status,
                ESN_NO=obj.ESN_NO,
                Responsibility_for_alarm_clearance=obj.Responsibility_for_alarm_clearance,
                TAC=obj.TAC,
                PCI_TDD_20=obj.PCI_TDD_20,
                PCI_TDD_10_20=obj.PCI_TDD_10_20,
                PCI_FDD_2100=obj.PCI_FDD_2100,
                PCI_FDD_1800=obj.PCI_FDD_1800,
                PCI_L900=obj.PCI_L900,
                PCI_5G=obj.PCI_5G,
                RSI_TDD_20=obj.RSI_TDD_20,
                RSI_TDD_10_20=obj.RSI_TDD_10_20,
                RSI_FDD_2100=obj.RSI_FDD_2100,
                RSI_FDD_1800=obj.RSI_FDD_1800,
                RSI_L900=obj.RSI_L900,
                RSI_5G=obj.RSI_5G,
                GPL=obj.GPL,
                Pre_Post_Check=obj.Pre_Post_Check,
                Activity_Type_SIWA=obj.Activity_Type_SIWA,
                Band_SIWA=obj.Band_SIWA,
                BSC_NAME=obj.BSC_NAME,
                BCF=obj.BCF,    

            )   
        else:
            new_record = Soft_At_Table.objects.create(
                upload_date=datetime.datetime.now().date(),
                unique_key=unique_key,  # Copy fields as required
                combination=obj.combination,
                IntegrationData=obj.IntegrationData,
                spoc_name=obj.spoc_name,
                offering_type=obj.offering_type,
                first_offering_date=obj.first_offering_date,
                soft_at_status= obj.soft_at_status,  # Change the status to 'pending'
                offering_date=obj.offering_date,
                acceptance_rejection_date=obj.acceptance_rejection_date,
                alarm_bucket=obj.alarm_bucket,
                alarm_details=obj.alarm_details,
                final_responsibility=obj.final_responsibility,
                workable_non_workable=obj.workable_non_workable,
                ubr_ms2_status=obj.ubr_ms2_status,
                ubr_link_id=obj.ubr_link_id,
                twamp_status=obj.twamp_status,
                status_check_date=obj.status_check_date,
                ageing_in_days=obj.ageing_in_days,
                actual_ageing=obj.actual_ageing,
                toco_partner=obj.toco_partner,
                support_required_ubr_team=obj.support_required_ubr_team,
                support_required_circle_team=obj.support_required_circle_team,
                support_required_noc_team=obj.support_required_noc_team,
                category=obj.category,
                problem_statement=obj.problem_statement,
                final_remarks=obj.final_remarks,
                ms1=obj.ms1,
                status_updated_by='auto_system',  # Example field to track update


                 # integration data
                OEM=obj.OEM,
                Integration_Date=obj.Integration_Date,
                CIRCLE=obj.CIRCLE,
                Activity_Name=obj.Activity_Name,
                Site_ID=obj.Site_ID,
                MO_NAME=obj.MO_NAME,
                LNBTS_ID=obj.LNBTS_ID,
                Technology_SIWA=obj.Technology_SIWA,
                OSS_Details=obj.OSS_Details,
                Cell_ID=obj.Cell_ID,
                CELL_COUNT=obj.CELL_COUNT,
                TRX_Count=obj.TRX_Count,
                PRE_ALARM=obj.PRE_ALARM,
                GPS_IP_CLK=obj.GPS_IP_CLK,
                RET=obj.RET,
                POST_VSWR=obj.POST_VSWR,
                POST_Alarms=obj.POST_Alarms,
                Activity_Mode=obj.Activity_Mode,
                CELL_STATUS=obj.CELL_STATUS,
                CTR_STATUS=obj.CTR_STATUS,
                Integration_Remark=obj.Integration_Remark,
                T2T4R=obj.T2T4R,
                BBU_TYPE=obj.BBU_TYPE,
                BB_CARD=obj.BB_CARD,
                RRU_Type=obj.RRU_Type,
                Media_Status=obj.Media_Status,
                Mplane_IP=obj.Mplane_IP,
                SCF_PREPARED_BY=obj.SCF_PREPARED_BY,
                SITE_INTEGRATE_BY=obj.SITE_INTEGRATE_BY,
                Site_Status=obj.Site_Status,
                External_Alarm_Confirmation=obj.External_Alarm_Confirmation,
                SOFT_AT_STATUS=obj.SOFT_AT_STATUS,
                LICENCE_Status=obj.LICENCE_Status,
                ESN_NO=obj.ESN_NO,
                Responsibility_for_alarm_clearance=obj.Responsibility_for_alarm_clearance,
                TAC=obj.TAC,
                PCI_TDD_20=obj.PCI_TDD_20,
                PCI_TDD_10_20=obj.PCI_TDD_10_20,
                PCI_FDD_2100=obj.PCI_FDD_2100,
                PCI_FDD_1800=obj.PCI_FDD_1800,
                PCI_L900=obj.PCI_L900,
                PCI_5G=obj.PCI_5G,
                RSI_TDD_20=obj.RSI_TDD_20,
                RSI_TDD_10_20=obj.RSI_TDD_10_20,
                RSI_FDD_2100=obj.RSI_FDD_2100,
                RSI_FDD_1800=obj.RSI_FDD_1800,
                RSI_L900=obj.RSI_L900,
                RSI_5G=obj.RSI_5G,
                GPL=obj.GPL,
                Pre_Post_Check=obj.Pre_Post_Check,
                Activity_Type_SIWA=obj.Activity_Type_SIWA,
                Band_SIWA=obj.Band_SIWA,
                BSC_NAME=obj.BSC_NAME,
                BCF=obj.BCF,    
            )



