# Generated by Django 4.1.3 on 2024-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEM', models.CharField(blank=True, max_length=100)),
                ('Integration_Date', models.DateField(null=True)),
                ('CIRCLE', models.CharField(blank=True, max_length=100)),
                ('Activity_Name', models.CharField(blank=True, max_length=100)),
                ('Site_ID', models.CharField(blank=True, max_length=100)),
                ('MO_NAME', models.CharField(blank=True, max_length=100)),
                ('LNBTS_ID', models.CharField(blank=True, max_length=100)),
                ('Technology', models.CharField(blank=True, max_length=100)),
                ('OSS_Details', models.CharField(blank=True, max_length=100)),
                ('Cell_ID', models.CharField(blank=True, max_length=100)),
                ('CELL_COUNT', models.IntegerField(null=True)),
                ('TRX_Count', models.IntegerField(null=True)),
                ('PRE_ALARM', models.CharField(blank=True, max_length=100)),
                ('GPS_IP_CLK', models.CharField(blank=True, max_length=100)),
                ('RET', models.CharField(blank=True, max_length=100)),
                ('POST_VSWR', models.CharField(blank=True, max_length=100)),
                ('POST_Alarms', models.CharField(blank=True, max_length=100)),
                ('Activity_Type', models.CharField(blank=True, max_length=100)),
                ('CELL_STATUS', models.CharField(blank=True, max_length=100)),
                ('CTR_STATUS', models.CharField(blank=True, max_length=100)),
                ('Integration_Remark', models.TextField(blank=True)),
                ('T2T4R', models.CharField(blank=True, max_length=100)),
                ('BBU_TYPE', models.CharField(blank=True, max_length=100)),
                ('BB_CARD', models.CharField(blank=True, max_length=100)),
                ('RRU_Type', models.CharField(blank=True, max_length=100)),
                ('Media_Status', models.CharField(blank=True, max_length=100)),
                ('Mplane_IP', models.CharField(blank=True, max_length=100)),
                ('SCF_PREPARED_BY', models.CharField(blank=True, max_length=100)),
                ('SITE_INTEGRATE_BY', models.CharField(blank=True, max_length=100)),
                ('Site_Status', models.CharField(blank=True, max_length=100)),
                ('External_Alarm_Confirmation', models.CharField(blank=True, max_length=100)),
                ('SOFT_AT_STATUS', models.CharField(blank=True, max_length=100)),
                ('LICENCE_Status', models.CharField(blank=True, max_length=100)),
                ('ESN_NO', models.CharField(blank=True, max_length=100)),
                ('Responsibility_for_alarm_clearance', models.CharField(blank=True, max_length=100)),
                ('TAC', models.CharField(blank=True, max_length=100)),
                ('PCI_TDD_20', models.IntegerField(null=True)),
                ('PCI_TDD_10_20', models.IntegerField(null=True)),
                ('PCI_FDD_2100', models.IntegerField(null=True)),
                ('PCI_FDD_1800', models.IntegerField(null=True)),
                ('PCI_L900', models.IntegerField(null=True)),
                ('RSI_TDD_20', models.IntegerField(null=True)),
                ('RSI_TDD_10_20', models.IntegerField(null=True)),
                ('RSI_FDD_2100', models.IntegerField(null=True)),
                ('RSI_FDD_1800', models.IntegerField(null=True)),
                ('RSI_L900', models.IntegerField(null=True)),
                ('GPL', models.CharField(blank=True, max_length=100)),
                ('Pre_Post_Check', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
