# Generated by Django 4.1.3 on 2024-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationdata',
            name='CELL_COUNT',
            field=models.CharField(blank=True, default='23', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='TRX_Count',
            field=models.CharField(blank=True, default='23', max_length=100),
            preserve_default=False,
        ),
    ]
