# Generated by Django 4.1.3 on 2024-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0002_alter_integrationdata_cell_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_FDD_2100',
            field=models.CharField(blank=True, default='12', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_L900',
            field=models.CharField(blank=True, default='25', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_TDD_10_20',
            field=models.CharField(blank=True, default='12', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_TDD_20',
            field=models.CharField(blank=True, default='23', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_FDD_1800',
            field=models.CharField(blank=True, default='23', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_FDD_2100',
            field=models.CharField(blank=True, default='23', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_L900',
            field=models.CharField(blank=True, default='12', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_TDD_10_20',
            field=models.CharField(blank=True, default='12', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_TDD_20',
            field=models.CharField(blank=True, default='12', max_length=100),
            preserve_default=False,
        ),
    ]
