# Generated by Django 4.1.3 on 2024-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0003_alter_integrationdata_pci_fdd_2100_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_FDD_1800',
            field=models.CharField(blank=True, default='12', max_length=100),
            preserve_default=False,
        ),
    ]
