# Generated by Django 4.1.3 on 2024-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0004_alter_integrationdata_pci_fdd_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationdata',
            name='Activity_Name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Activity_Type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='BBU_TYPE',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='BB_CARD',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='CELL_COUNT',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='CELL_STATUS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='CIRCLE',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='CTR_STATUS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Cell_ID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='ESN_NO',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='External_Alarm_Confirmation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='GPL',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='GPS_IP_CLK',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='LICENCE_Status',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='LNBTS_ID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='MO_NAME',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Media_Status',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Mplane_IP',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='OEM',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='OSS_Details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_FDD_1800',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_FDD_2100',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_L900',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_TDD_10_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PCI_TDD_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='POST_Alarms',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='POST_VSWR',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='PRE_ALARM',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Pre_Post_Check',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RET',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RRU_Type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_FDD_1800',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_FDD_2100',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_L900',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_TDD_10_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='RSI_TDD_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Responsibility_for_alarm_clearance',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='SCF_PREPARED_BY',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='SITE_INTEGRATE_BY',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='SOFT_AT_STATUS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Site_ID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Site_Status',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='T2T4R',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='TAC',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='TRX_Count',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='integrationdata',
            name='Technology',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
