# Generated by Django 4.1.3 on 2024-05-16 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0005_alter_integrationdata_activity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationdata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
