# Generated by Django 4.1.3 on 2024-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0007_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to='IntegrationTracker/documents/'),
        ),
    ]
