# Generated by Django 4.1.3 on 2024-07-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0008_alter_document_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationdata',
            name='PCI_5G',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='RSI_5G',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
