# Generated by Django 4.1.3 on 2024-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0009_integrationdata_pci_5g_integrationdata_rsi_5g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationdata',
            old_name='Activity_Type',
            new_name='Activity_Mode',
        ),
        migrations.RenameField(
            model_name='integrationdata',
            old_name='Technology',
            new_name='Technology_SIWA',
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='Activity_Type_SIWA',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='Band_SIWA',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
