# Generated by Django 4.1.3 on 2024-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0010_rename_activity_type_integrationdata_activity_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationdata',
            name='BCF',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='BSC_NAME',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
