# Generated by Django 4.1.3 on 2024-09-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0011_integrationdata_bcf_integrationdata_bsc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationdata',
            name='unique_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
