# Generated by Django 4.1.3 on 2025-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0012_integrationdata_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationdata',
            name='CRQ',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='Customer_Approval',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
