# Generated by Django 4.1.3 on 2025-02-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0013_integrationdata_crq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationdata',
            name='Allocated_Tech',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='Deployed_Tech',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='Old_Site_ID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='Old_Site_Tech',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
