# Generated by Django 4.1.3 on 2025-02-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0014_integrationdata_allocated_tech_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relocation_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(max_length=255)),
                ('old_site_id', models.CharField(max_length=255)),
                ('new_site_id', models.CharField(max_length=255)),
                ('integration_date', models.DateField()),
                ('ms1_date', models.DateField()),
                ('old_site_technology', models.CharField(max_length=255)),
                ('allocated_technology', models.CharField(max_length=255)),
                ('deployed_technology', models.CharField(max_length=255)),
                ('deviation', models.CharField(max_length=255)),
                ('no_of_deviated_tech', models.IntegerField()),
                ('old_site_locked_date', models.DateField()),
                ('new_site_unlock_date', models.DateField()),
                ('old_site_traffic', models.CharField(max_length=255)),
                ('existing_traffic', models.CharField(max_length=255)),
                ('old_site_admin_status', models.CharField(max_length=255)),
                ('new_site_admin_status', models.CharField(max_length=255)),
                ('both_site_unlocked', models.CharField(max_length=255)),
                ('both_site_locked', models.CharField(max_length=255)),
                ('pre_less_than_3_mbps', models.CharField(max_length=255)),
                ('current_less_than_3_mbps', models.CharField(max_length=255)),
            ],
        ),
    ]
