# Generated by Django 4.1.3 on 2025-02-03 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0016_alter_relocation_tracker_integration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relocation_tracker',
            name='integration_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 3, 9, 58, 27, 242314, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='ms1_date',
            field=models.DateField(null=True),
        ),
    ]
