# Generated by Django 4.1.3 on 2025-02-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0017_alter_relocation_tracker_integration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relocation_tracker',
            name='allocated_technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='both_site_locked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='both_site_unlocked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='circle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='current_less_than_3_mbps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='deployed_technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='deviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='existing_traffic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='integration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='new_site_admin_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='new_site_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='new_site_unlock_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='no_of_deviated_tech',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='old_site_admin_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='old_site_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='old_site_locked_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='old_site_technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='old_site_traffic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relocation_tracker',
            name='pre_less_than_3_mbps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
