# Generated by Django 4.1.3 on 2025-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0018_alter_relocation_tracker_allocated_technology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relocation_tracker',
            old_name='old_site_traffic',
            new_name='old_site_traffic_fixed',
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='allocated_vs_deployed_tech',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='old_site_traffic_variable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='old_vs_deployed_tech',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
