# Generated by Django 4.1.3 on 2025-02-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0020_daily_post_traffic_daily_pre_traffic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocation_tracker',
            name='ix_unique_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
