# Generated by Django 4.1.3 on 2025-02-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0022_rename_deviation_relocation_tracker_allocated_vs_deployed_tech_deviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocation_tracker',
            name='payload',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
