# Generated by Django 4.1.3 on 2025-02-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0023_relocation_tracker_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relocation_tracker',
            old_name='payload',
            new_name='payload_dip',
        ),
    ]
