# Generated by Django 4.1.3 on 2025-02-05 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0024_rename_payload_relocation_tracker_payload_dip'),
    ]

    operations = [
        migrations.AddField(
            model_name='relocation_tracker',
            name='approval_given_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='new_site_unlocked_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='old_site_locked_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='site_locked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
