# Generated by Django 4.1.3 on 2025-02-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0026_old_site_locked_unlocked_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_site_locked_unlocked_date',
            name='Relocation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_site_locked_unlocked_date', to='IntegrationTracker.relocation_tracker'),
        ),
        migrations.AlterField(
            model_name='old_site_locked_unlocked_date',
            name='Relocation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_site_locked_unlocked_date', to='IntegrationTracker.relocation_tracker'),
        ),
    ]
