# Generated by Django 4.1.3 on 2025-02-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0027_alter_new_site_locked_unlocked_date_relocation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relocation_tracker',
            name='approval_given_by',
        ),
        migrations.RemoveField(
            model_name='relocation_tracker',
            name='new_site_unlock_date',
        ),
        migrations.RemoveField(
            model_name='relocation_tracker',
            name='new_site_unlocked_datetime',
        ),
        migrations.RemoveField(
            model_name='relocation_tracker',
            name='old_site_locked_date',
        ),
        migrations.RemoveField(
            model_name='relocation_tracker',
            name='old_site_locked_datetime',
        ),
        migrations.RemoveField(
            model_name='relocation_tracker',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='relocation_tracker',
            name='site_locked_by',
        ),
    ]
