# Generated by Django 4.1.3 on 2025-02-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0028_remove_relocation_tracker_approval_given_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_site_locked_unlocked_date',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='old_site_locked_unlocked_date',
            name='date_time',
        ),
    ]
