# Generated by Django 4.1.3 on 2025-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0029_remove_new_site_locked_unlocked_date_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_site_locked_unlocked_date',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='old_site_locked_unlocked_date',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
