# Generated by Django 4.1.3 on 2025-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0030_new_site_locked_unlocked_date_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_site_locked_unlocked_date',
            name='OEM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_site_locked_unlocked_date',
            name='Technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_site_locked_unlocked_date',
            name='circle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='new_site_locked_unlocked_date',
            name='no_of_BBUs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='old_site_locked_unlocked_date',
            name='OEM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='old_site_locked_unlocked_date',
            name='Technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='old_site_locked_unlocked_date',
            name='circle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='old_site_locked_unlocked_date',
            name='no_of_BBUs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='mo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='no_of_BBUs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
