# Generated by Django 4.1.3 on 2025-03-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0031_new_site_locked_unlocked_date_oem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(max_length=10, unique=True)),
                ('approver_name', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='integrationdata',
            name='NO_OF_BBU',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='OEM',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='Remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relocation_tracker',
            name='ms2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='new_site_locked_unlocked_date',
            name='purpose',
            field=models.CharField(blank=True, choices=[('EMF', 'EMF'), ('SCFT', 'SCFT'), ('MS1', 'MS1'), ('others', 'others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='old_site_locked_unlocked_date',
            name='purpose',
            field=models.CharField(blank=True, choices=[('EMF', 'EMF'), ('SCFT', 'SCFT'), ('MS1', 'MS1'), ('others', 'others')], max_length=255, null=True),
        ),
    ]
