# Generated by Django 4.1.3 on 2025-03-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0032_approval_integrationdata_no_of_bbu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relocation_tracker',
            old_name='email_sent',
            new_name='mail_sent',
        ),
    ]
