# Generated by Django 4.1.3 on 2025-03-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0033_rename_email_sent_relocation_tracker_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_site_locked_unlocked_date',
            name='Remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='old_site_locked_unlocked_date',
            name='Remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
