# Generated by Django 4.1.3 on 2025-03-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0034_new_site_locked_unlocked_date_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_site_locked_unlocked_date',
            old_name='Remark',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='old_site_locked_unlocked_date',
            old_name='Remark',
            new_name='remark',
        ),
    ]
