# Generated by Django 5.2 on 2025-05-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrationTracker', '0035_rename_remark_new_site_locked_unlocked_date_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed_pre_traffic',
            name='traffic',
            field=models.FloatField(null=True),
        ),
    ]
