# Generated by Django 4.1.3 on 2024-03-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZTE_HR_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.CharField(max_length=500, null=True)),
                ('MO_FDD', models.CharField(max_length=500, null=True)),
                ('MO_TDD', models.CharField(max_length=500, null=True)),
                ('ZTE_parameter', models.CharField(max_length=500, null=True)),
                ('Parameter_type', models.CharField(max_length=500, null=True)),
                ('L2100', models.CharField(max_length=1000, null=True)),
                ('L1800', models.CharField(max_length=1000, null=True)),
                ('TD20', models.CharField(max_length=1000, null=True)),
                ('Meascinfigindx', models.CharField(max_length=500, null=True)),
                ('Category', models.CharField(max_length=500, null=True)),
                ('Remarks', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
