# Generated by Django 4.1.3 on 2023-05-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='performance_At_upload_status',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('update_status', models.CharField(blank=True, max_length=100, null=True)),
                ('Remark', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='performanceAT',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CIRCLE', models.CharField(max_length=100)),
                ('SITE_ID', models.CharField(max_length=100)),
                ('UNIQUE_ID', models.CharField(max_length=100)),
                ('ENODEB_ID', models.CharField(max_length=100, null=True)),
                ('BAND', models.CharField(max_length=100, null=True)),
                ('Circle_Project', models.CharField(max_length=100)),
                ('OEM_NAME_Nokia_ZTE_Ericsson_Huawei', models.CharField(max_length=100, null=True)),
                ('MS1', models.DateField(null=True)),
                ('Performance_AT_Status_Accepted_Rejected', models.CharField(max_length=100)),
                ('Internal_Ms1_Vs_Ms2_n_days', models.CharField(max_length=100, null=True)),
                ('Total_Allocation', models.CharField(max_length=100, null=True)),
                ('Project', models.CharField(max_length=100, null=True)),
                ('Acceptance_Status_Accepted_Offered_Pending', models.CharField(max_length=100, null=True)),
                ('Accepted_Offered_Date', models.DateField(null=True)),
                ('Pending_Reason', models.CharField(max_length=100, null=True)),
                ('Action_Plan', models.CharField(max_length=100, null=True)),
                ('Ownership', models.CharField(max_length=100, null=True)),
                ('Ageing', models.CharField(max_length=100, null=True)),
                ('upload_date', models.DateField(null=True)),
            ],
        ),
    ]
