# Generated by Django 4.1.3 on 2023-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performance_AT_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceat',
            name='UNIQUE_ID',
            field=models.CharField(max_length=500),
        ),
    ]
