# Generated by Django 4.1.3 on 2023-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performance_AT_APP', '0002_alter_performanceat_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceat',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
