# Generated by Django 4.1.3 on 2023-05-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performance_AT_APP', '0003_alter_performanceat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance_at_upload_status',
            name='Remark',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performance_at_upload_status',
            name='Site_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performance_at_upload_status',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performance_at_upload_status',
            name='update_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Acceptance_Status_Accepted_Offered_Pending',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Action_Plan',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Ageing',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='BAND',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='CIRCLE',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Circle_Project',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='ENODEB_ID',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Internal_Ms1_Vs_Ms2_n_days',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='OEM_NAME_Nokia_ZTE_Ericsson_Huawei',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Ownership',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Pending_Reason',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Performance_AT_Status_Accepted_Rejected',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Project',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='SITE_ID',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='performanceat',
            name='Total_Allocation',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
