# Generated by Django 4.1.3 on 2024-01-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Performance_AT_APP', '0004_alter_performance_at_upload_status_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceat',
            old_name='Accepted_Offered_Date',
            new_name='Acceptance_Date',
        ),
        migrations.RenameField(
            model_name='performanceat',
            old_name='Acceptance_Status_Accepted_Offered_Pending',
            new_name='Action_plan_Remarks',
        ),
        migrations.RenameField(
            model_name='performanceat',
            old_name='Action_Plan',
            new_name='Analysis',
        ),
        migrations.RenameField(
            model_name='performanceat',
            old_name='BAND',
            new_name='Impacted_KPIs',
        ),
        migrations.RenameField(
            model_name='performanceat',
            old_name='Circle_Project',
            new_name='No_of_Pending_layers',
        ),
        migrations.RenameField(
            model_name='performanceat',
            old_name='ENODEB_ID',
            new_name='Only_KPI_AT_pending',
        ),
        migrations.RenameField(
            model_name='performanceat',
            old_name='Pending_Reason',
            new_name='Ownership_Mcom_Internal',
        ),
        migrations.RenameField(
            model_name='performanceat',
            old_name='Total_Allocation',
            new_name='RCA_for_high_Ageing',
        ),
        migrations.RemoveField(
            model_name='performanceat',
            name='Performance_AT_Status_Accepted_Rejected',
        ),
        migrations.AddField(
            model_name='performanceat',
            name='Reason_of_new_workable_date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='performanceat',
            name='Status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='performanceat',
            name='TAT',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='performanceat',
            name='Tool_Bucket',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='performanceat',
            name='Workable_date_If_pending_due_to_other_reason',
            field=models.DateField(null=True),
        ),
    ]
