# Generated by Django 4.1.3 on 2024-09-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IntegrationTracker', '0012_integrationdata_unique_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_At_upload_status',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Site_id', models.CharField(blank=True, max_length=500, null=True)),
                ('UNIQUE_ID', models.CharField(blank=True, max_length=500, null=True)),
                ('update_status', models.CharField(blank=True, max_length=500, null=True)),
                ('Remark', models.TextField(blank=True, max_length=500, null=True)),
                ('CIRCLE', models.CharField(blank=True, max_length=500, null=True)),
                ('SITE_ID', models.CharField(blank=True, max_length=500, null=True)),
                ('BAND', models.CharField(blank=True, max_length=500, null=True)),
                ('OEM_NAME', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'unique_together': {('CIRCLE', 'SITE_ID', 'BAND', 'UNIQUE_ID', 'OEM_NAME')},
            },
        ),
        migrations.CreateModel(
            name='Soft_At_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('unique_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('spoc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('offering_type', models.CharField(blank=True, max_length=255, null=True)),
                ('first_offering_date', models.DateField(blank=True, null=True)),
                ('soft_at_status', models.CharField(blank=True, max_length=255, null=True)),
                ('offering_date', models.DateField(blank=True, null=True)),
                ('acceptance_rejection_date', models.DateField(blank=True, null=True)),
                ('alarm_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('alarm_details', models.TextField(blank=True, null=True)),
                ('final_responsibility', models.CharField(blank=True, max_length=255, null=True)),
                ('workable_non_workable', models.CharField(blank=True, max_length=255, null=True)),
                ('ubr_ms2_status', models.CharField(blank=True, max_length=255, null=True)),
                ('ubr_link_id', models.CharField(blank=True, max_length=255, null=True)),
                ('twamp_status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_check_date', models.DateField(blank=True, null=True)),
                ('ageing_in_days', models.IntegerField(blank=True, null=True)),
                ('actual_ageing', models.CharField(blank=True, max_length=255, null=True)),
                ('toco_partner', models.CharField(blank=True, max_length=255, null=True)),
                ('support_required_ubr_team', models.BooleanField(blank=True, null=True)),
                ('support_required_circle_team', models.BooleanField(blank=True, null=True)),
                ('support_required_noc_team', models.BooleanField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('final_remarks', models.TextField(blank=True, null=True)),
                ('ms1', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_updated_by', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('IntegrationData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IntegrationTracker.integrationdata')),
            ],
        ),
    ]
