# Generated by Django 4.1.3 on 2024-09-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOFT_AT_VINAY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_table',
            name='Activity_Mode',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Activity_Name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Activity_Type_SIWA',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='BBU_TYPE',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='BB_CARD',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='BCF',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='BSC_NAME',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Band_SIWA',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='CELL_COUNT',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='CELL_STATUS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='CIRCLE',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='CTR_STATUS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Cell_ID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='ESN_NO',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='External_Alarm_Confirmation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='GPL',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='GPS_IP_CLK',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Integration_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Integration_Remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='LICENCE_Status',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='LNBTS_ID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='MO_NAME',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Media_Status',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Mplane_IP',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='OEM',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='OSS_Details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='PCI_5G',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='PCI_FDD_1800',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='PCI_FDD_2100',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='PCI_L900',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='PCI_TDD_10_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='PCI_TDD_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='POST_Alarms',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='POST_VSWR',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='PRE_ALARM',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Pre_Post_Check',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RET',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RRU_Type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RSI_5G',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RSI_FDD_1800',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RSI_FDD_2100',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RSI_L900',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RSI_TDD_10_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='RSI_TDD_20',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Responsibility_for_alarm_clearance',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='SCF_PREPARED_BY',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='SITE_INTEGRATE_BY',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='SOFT_AT_STATUS',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Site_ID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Site_Status',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='T2T4R',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='TAC',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='TRX_Count',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Technology_SIWA',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
