# Generated by Django 4.1.3 on 2024-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOFT_AT_VINAY', '0002_soft_at_table_activity_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soft_at_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='soft_at_table',
            name='unique_key',
            field=models.CharField(default=0, max_length=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
