# Generated by Django 4.1.3 on 2024-10-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOFT_AT_VINAY', '0003_remove_soft_at_table_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_table',
            name='combination',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
