# Generated by Django 4.1.3 on 2024-10-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOFT_AT_VINAY', '0004_soft_at_table_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_table',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
    ]
