# Generated by Django 4.1.3 on 2024-10-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOFT_AT_VINAY', '0005_soft_at_table_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_at_table',
            name='support_required_circle_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='soft_at_table',
            name='support_required_noc_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='soft_at_table',
            name='support_required_ubr_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
