# Generated by Django 4.1.3 on 2024-10-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOFT_AT_VINAY', '0006_alter_soft_at_table_support_required_circle_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_at_table',
            name='Activity_Type_SIWA',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
