# Generated by Django 4.1.3 on 2024-10-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOFT_AT_VINAY', '0008_alter_soft_at_table_activity_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_at_table',
            name='ESN_NO',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
