# Generated by Django 4.1.3 on 2023-09-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_report',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('YEAR', models.PositiveIntegerField()),
                ('MONTH', models.CharField(max_length=500)),
                ('circle', models.CharField(max_length=500)),
                ('project', models.CharField(max_length=500)),
                ('COMPATITOR', models.CharField(max_length=500)),
                ('DONE_COUNT', models.IntegerField(max_length=500, null=True)),
                ('PROJECTED_COUNT', models.IntegerField(max_length=500)),
            ],
        ),
    ]
