# Generated by Django 4.1.3 on 2023-09-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDP', '0002_alter_upload_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_report',
            name='DONE_COUNT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='upload_report',
            name='PROJECTED_COUNT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='upload_report',
            name='YEAR',
            field=models.PositiveIntegerField(),
        ),
    ]
