# Generated by Django 4.1.3 on 2023-09-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDP', '0003_alter_upload_report_done_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_report',
            new_name='upload_report_table',
        ),
    ]
