# Generated by Django 4.1.3 on 2023-09-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDP', '0004_rename_upload_report_upload_report_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_report_table',
            name='DONE_COUNT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload_report_table',
            name='PROJECTED_COUNT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
