# Generated by Django 4.1.3 on 2024-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDP', '0005_alter_upload_report_table_done_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('aop', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=100)),
                ('airtel_projection', models.IntegerField()),
                ('mobilecomm_projection', models.IntegerField()),
            ],
            options={
                'db_table': 'Projected_data',
                'unique_together': {('circle', 'month', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ActualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('aop', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=100)),
                ('airtel_actual', models.IntegerField()),
                ('mobilecomm_actual', models.IntegerField()),
                ('vedang_actual', models.IntegerField()),
                ('frog_cell_actual', models.IntegerField()),
                ('ariel_actual', models.IntegerField()),
                ('others_actual', models.IntegerField()),
            ],
            options={
                'db_table': 'Actual_data',
                'unique_together': {('circle', 'month', 'project')},
            },
        ),
    ]
