# Generated by Django 4.1.3 on 2024-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDP', '0006_projecteddata_actualdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualdata',
            name='Ericsson_Actual',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualdata',
            name='Nokia_Actual',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
