# Generated by Django 4.1.3 on 2024-05-24 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MDP', '0007_actualdata_ericsson_actual_actualdata_nokia_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualdata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='actualdata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualdata',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='projecteddata',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecteddata',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecteddata',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
