# Generated by Django 4.1.3 on 2024-06-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDP', '0008_actualdata_updated_date_actualdata_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actualdata',
            unique_together={('aop', 'circle', 'month', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='projecteddata',
            unique_together={('aop', 'circle', 'month', 'project')},
        ),
    ]
