# Generated by Django 4.1.3 on 2024-01-29 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/')),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Employee_Code', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Designation', models.CharField(max_length=500)),
                ('Contact', models.BigIntegerField()),
                ('Office_Address', models.TextField()),
                ('Home_Address', models.TextField()),
                ('COUNTRY', models.CharField(default='India', max_length=100)),
                ('STATE', models.CharField(default='Delhi', max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
