# Generated by Django 4.1.3 on 2024-05-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_usercircle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercircle',
            name='user_catagory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
