# Generated by Django 4.1.3 on 2023-06-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpr_dpr2_table',
            old_name='Performance_AT_Status_Accepted_Rejected_Offered_Pending_Dismantle',
            new_name='Performance_AT_Status_Accept_Rejected_Offered_Pending_Dismantle',
        ),
    ]
