# Generated by Django 4.1.3 on 2023-06-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0002_rename_performance_at_status_accepted_rejected_offered_pending_dismantle_wpr_dpr2_table_performance_'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpr_dpr2_table',
            name='Additional_DPR_Remarks',
            field=models.CharField(default='sd', max_length=500),
            preserve_default=False,
        ),
    ]
