# Generated by Django 4.1.3 on 2023-06-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0003_wpr_dpr2_table_additional_dpr_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='Ms1_Vs_Ms2',
            field=models.CharField(default='sd', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='RFAI_Vs_MS1',
            field=models.CharField(default='dsd', max_length=500),
            preserve_default=False,
        ),
    ]
