# Generated by Django 4.1.3 on 2023-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0004_alter_wpr_dpr2_table_ms1_vs_ms2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='DEVIATION_APPROVAL_MAIL_RX_DATE_IF_APPLICABLE',
            field=models.DateField(null=True),
        ),
    ]
