# Generated by Django 4.1.3 on 2023-06-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0005_alter_wpr_dpr2_table_deviation_approval_mail_rx_date_if_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='SCFT_COMPLETION_DATE',
            field=models.DateField(null=True),
        ),
    ]
