# Generated by Django 4.1.3 on 2023-06-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0006_alter_wpr_dpr2_table_scft_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='Allocation_Date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
