# Generated by Django 4.1.3 on 2023-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0007_alter_wpr_dpr2_table_allocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='Ms1_Vs_Ms2',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
