# Generated by Django 4.1.3 on 2023-06-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0008_alter_wpr_dpr2_table_ms1_vs_ms2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='RFAI_Vs_MS1',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
