# Generated by Django 4.1.3 on 2023-06-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0009_alter_wpr_dpr2_table_rfai_vs_ms1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='MS1_Vs_Soft_AT_Acceptance_Ageing',
            field=models.DateField(blank=True),
        ),
    ]
