# Generated by Django 4.1.3 on 2023-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0010_alter_wpr_dpr2_table_ms1_vs_soft_at_acceptance_ageing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='Allocation_Date',
            field=models.DateField(null=True),
        ),
    ]
