# Generated by Django 4.1.3 on 2023-06-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0011_alter_wpr_dpr2_table_allocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='MS1_Vs_PHY_AT_Acceptance_Ageing',
            field=models.DateField(null=True),
        ),
    ]
