# Generated by Django 4.1.3 on 2023-06-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WPR_DPR2', '0012_alter_wpr_dpr2_table_ms1_vs_phy_at_acceptance_ageing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='MS1_Vs_Performance_AT_Acceptance_Ageing',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='wpr_dpr2_table',
            name='MS1_Vs_Soft_AT_Acceptance_Ageing',
            field=models.DateField(null=True),
        ),
    ]
