# Generated by Django 4.1.3 on 2024-02-13 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UBR_Soft_Phy_AT_Rejection_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Circle', models.CharField(max_length=500, null=True)),
                ('Site_ID', models.CharField(max_length=500, null=True)),
                ('Site_Type', models.CharField(max_length=500, null=True)),
                ('TSP', models.CharField(max_length=500, null=True)),
                ('Link_Id', models.CharField(max_length=500, null=True)),
                ('RA_Number', models.CharField(max_length=500, null=True)),
                ('CKT_ID', models.CharField(max_length=500, null=True)),
                ('UBR_Make_OEM', models.CharField(max_length=500, null=True)),
                ('UBR_Model', models.CharField(max_length=500, null=True)),
                ('Site_A_IP', models.CharField(max_length=500, null=True)),
                ('Site_B_IP', models.CharField(max_length=500, null=True)),
                ('Re_offer', models.CharField(max_length=500, null=True)),
                ('Soft_Physical', models.CharField(max_length=500, null=True)),
                ('Offered_Date', models.DateField(null=True)),
                ('AT_Status', models.CharField(max_length=500, null=True)),
                ('Reasons', models.CharField(max_length=500, null=True)),
                ('Date_Time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
