# Generated by Django 4.1.3 on 2024-05-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkillTable',
            fields=[
                ('emp_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('circle', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('manager_emp_code', models.CharField(max_length=20)),
                ('reporting_manager_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('domain', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('current_role', models.CharField(max_length=100)),
                ('key_responsibility', models.TextField()),
                ('skillsets', models.TextField()),
                ('oem', models.CharField(max_length=100)),
                ('total_exp', models.FloatField()),
                ('mobilecomm_exp', models.FloatField()),
                ('previous_org1', models.CharField(max_length=100)),
                ('previous_org2', models.CharField(max_length=100)),
                ('previous_org3', models.CharField(max_length=100)),
                ('current_designation', models.CharField(max_length=100)),
                ('working_status', models.CharField(max_length=100)),
                ('team_category', models.CharField(max_length=100)),
            ],
        ),
    ]
