# Generated by Django 4.1.3 on 2024-05-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_skills', '0002_alter_employeeskilltable_previous_org1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskilltable',
            name='doj',
            field=models.DateField(blank=True),
        ),
    ]
