# Generated by Django 4.1.3 on 2024-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_skills', '0004_alter_employeeskilltable_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskilltable',
            name='current_circle',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
