# Generated by Django 4.1.3 on 2024-05-12 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_skills', '0005_employeeskilltable_current_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskilltable',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeeskilltable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeskilltable',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
