# Generated by Django 4.1.3 on 2024-05-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_skills', '0006_employeeskilltable_active_employeeskilltable_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskilltable',
            name='deleted_by',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
