# Generated by Django 4.1.3 on 2024-05-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_skills', '0007_employeeskilltable_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeskilltable',
            name='delete_remark',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
