# Generated by Django 5.2.1 on 2025-05-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('parameter_name', models.CharField(max_length=200)),
                ('expected_value', models.CharField(max_length=500)),
            ],
        ),
    ]
