# Generated by Django 5.2.1 on 2025-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Nokia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedparameter',
            name='expected_value',
            field=models.TextField(),
        ),
    ]
