# Generated by Django 5.2.1 on 2025-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_Nokia', '0002_alter_expectedparameter_expected_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MO_Class', models.CharField(max_length=500)),
                ('Parameter', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='expectedparameter',
            name='expected_value',
            field=models.CharField(max_length=500),
        ),
    ]
