# Generated by Django 4.1.3 on 2023-05-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0005_soft_at_table_alarm_bucket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soft_at_table',
            old_name='UNQUI_ID',
            new_name='UNIQUE_ID',
        ),
    ]
