# Generated by Django 4.1.3 on 2023-05-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0006_rename_unqui_id_soft_at_table_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_table',
            name='Ageing',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
