# Generated by Django 4.1.3 on 2023-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0007_soft_at_table_ageing'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_table',
            name='Upload_date',
            field=models.DateField(null=True),
        ),
    ]
