# Generated by Django 4.1.3 on 2023-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0008_soft_at_table_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_table',
            name='Remarks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
