# Generated by Django 4.1.3 on 2023-05-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0009_soft_at_table_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_at_table',
            name='Remarks',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
