# Generated by Django 4.1.3 on 2024-12-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Count_Rna_Payload_Tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_counter_table_data',
            name='Pre_Remarks',
            field=models.JSONField(default=list, help_text='Preliminary remarks about the ticket.'),
        ),
    ]
