# Generated by Django 4.1.3 on 2024-12-30 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Count_Rna_Payload_Tool', '0002_alter_ticket_counter_table_data_pre_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_4G_KPI_REPORT',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated the record.', max_length=500, null=True)),
                ('daily_4g_kpi_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="This is a unique identifier for the daily kpi's", primary_key=True, serialize=False, unique=True)),
                ('kpi_name', models.CharField(blank=True, default='No KPI Found', max_length=500, null=True)),
                ('Short_name', models.CharField(help_text='Short_name Corressponding to 4g_kpi', max_length=500)),
                ('Date', models.DateField(blank=True, help_text='The date of the event (YYYY-MM-DD).', null=True)),
                ('Site_ID', models.CharField(blank=True, help_text='Site identifier.', max_length=500, null=True)),
                ('oem', models.CharField(blank=True, help_text='The Original Equipment Manufacturer of the software', max_length=100, null=True)),
                ('ECGI_4G', models.CharField(blank=True, help_text='this is a 4G_ECGI Field...', max_length=500, null=True)),
                ('week_1_val', models.FloatField(default=0, max_length=500)),
                ('week_2_val', models.FloatField(default=0, max_length=500)),
                ('date_1_val', models.FloatField(default=0, max_length=500)),
                ('date_2_val', models.FloatField(default=0, max_length=500)),
                ('date_3_val', models.FloatField(default=0, max_length=500)),
                ('date_4_val', models.FloatField(default=0, max_length=500)),
                ('date_5_val', models.FloatField(default=0, max_length=500)),
                ('date_6_val', models.FloatField(default=0, max_length=500)),
                ('date_7_val', models.FloatField(default=0, max_length=500)),
                ('date_8_val', models.FloatField(default=0, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
