# Generated by Django 4.1.3 on 2025-01-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Count_Rna_Payload_Tool', '0003_daily_4g_kpi_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_counter_table_data',
            name='rca_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
