# Generated by Django 4.1.3 on 2025-01-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Count_Rna_Payload_Tool', '0004_ticket_counter_table_data_rca_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_counter_table_data',
            name='rca_feedback',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
