# Generated by Django 4.1.3 on 2025-01-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Count_Rna_Payload_Tool', '0006_level1_level2_level3_level4_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_counter_table_data',
            name='ticket_type',
            field=models.CharField(blank=True, help_text='Type of the ticket.', max_length=500, null=True),
        ),
    ]
