# Generated by Django 4.1.3 on 2025-02-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Count_Rna_Payload_Tool', '0007_ticket_counter_table_data_ticket_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket_counter_table_data',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='ticket_counter_table_data',
            name='unique_shortname_date',
        ),
    ]
