# Generated by Django 4.1.3 on 2023-08-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_rna_Pld_alarm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rna_pyl_alrm',
            name='Performance_AT_Status_Accepted_Rejected_Offered_Pending_Dismantle',
            field=models.CharField(db_column='Performance_AT_Status_Accepted_Rejected_Offered_Pending_Dismantle', max_length=300),
        ),
        migrations.RenameField(
            model_name='rna_pyl_alrm',
            old_name='Performance_AT_Status_Accepted_Rejected_Offered_Pending_Dismantle',
            new_name='performanceATStatusAcceptedRejectedOfferedPendingDismantle',
        ),
    ]
