# Generated by Django 4.1.3 on 2024-07-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUDIT_TOOL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
