# Generated by Django 4.1.3 on 2024-07-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUDIT_TOOL', '0002_alter_task_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='app_name',
            field=models.CharField(default='AUDIT_TOOL', max_length=500),
            preserve_default=False,
        ),
    ]
