from django.db import models

class AlokTrackerModel(models.Model):
    # unique_id = models.CharField(max_length=50, null=True, blank=True)
    circle = models.CharField(max_length=100, null=True, blank=True)
    site_tagging = models.CharField(max_length=100, null=True, blank=True)
    old_toco_name = models.CharField(max_length=100, null=True, blank=True)
    old_site_id = models.CharField(max_length=100, null=True, blank=True)
    new_site_id = models.CharField(max_length=100, null=True, blank=True)
    new_toco_name = models.CharField(max_length=100, null=True, blank=True)
    sr_number = models.CharField(max_length=100, null=True, blank=True)
    ran_oem = models.CharField(max_length=100, null=True, blank=True)
    media_type = models.CharField(max_length=100, null=True, blank=True)
    mw_oem = models.CharField(max_length=100, null=True, blank=True)
    relocation_method = models.CharField(max_length=100, null=True, blank=True)
    relocation_type = models.CharField(max_length=100, null=True, blank=True)
    old_site_band = models.CharField(max_length=100, null=True, blank=True)
    new_site_band = models.CharField(max_length=100, null=True, blank=True)
    rfai_date = models.DateField(null=True, blank=True)
    allocation_date = models.DateField(null=True, blank=True)
    rfai_survey_date = models.DateField(null=True, blank=True)
    rfai_survey_done_date = models.DateField(null=True, blank=True)
    mo_punch_date = models.DateField(null=True, blank=True)
    material_dispatch_date = models.DateField(null=True, blank=True)
    material_delivered_date = models.DateField(null=True, blank=True)
    installation_start_date = models.DateField(null=True, blank=True)
    installation_end_date = models.DateField(null=True, blank=True)
    integration_date = models.DateField(null=True, blank=True)
    emf_submission_date = models.DateField(null=True, blank=True)
    ran_lkf_status = models.CharField(max_length=100, null=True, blank=True)
    alarm_status = models.CharField(max_length=100, null=True, blank=True)
    alarm_rectification_done_date = models.DateField(null=True, blank=True)
    scft_done_date = models.DateField(null=True, blank=True)
    scft_offered_date = models.DateField(null=True, blank=True)
    ran_pat_offer_date = models.DateField(null=True, blank=True)
    ran_sat_offer_date = models.DateField(null=True, blank=True)
    mw_plan_id = models.CharField(max_length=100, null=True, blank=True)
    mw_phy_at_offer_date = models.DateField(null=True, blank=True)
    rsl_value_status = models.CharField(max_length=100, null=True, blank=True)
    enm_status = models.CharField(max_length=100, null=True, blank=True)
    mw_lkf = models.CharField(max_length=100, null=True, blank=True)
    mw_soft_at_offer_date = models.DateField(null=True, blank=True)
    mw_ms1_date_mids = models.DateField(null=True, blank=True)
    site_onair_date = models.DateField(null=True, blank=True)
    i_deploy_onair_date = models.DateField(null=True, blank=True)
    five_g_onair_date = models.DateField(null=True, blank=True)
    ran_pat_accepted_date = models.DateField(null=True, blank=True)
    ran_sat_accepted_date = models.DateField(null=True, blank=True)
    mw_phy_at_accepted_date = models.DateField(null=True, blank=True)
    mw_soft_at_accepted_date = models.DateField(null=True, blank=True)
    scft_accepted_date = models.DateField(null=True, blank=True)
    kpi_at_offer_date = models.DateField(null=True, blank=True)
    kpi_at_accepted_date = models.DateField(null=True, blank=True)
    four_g_ms2_date = models.DateField(null=True, blank=True)
    five_g_ms2_date = models.DateField(null=True, blank=True)
    last_updated_date = models.DateTimeField(null=True, blank=False, auto_now=True)
    last_updated_by = models.CharField(max_length=255,null=True, blank=True)

    class Meta:
        db_table = "relocation_site_project_tracker"

    def __str__(self):
        return f"{self.circle} - {self.new_site_id}"
