from django.urls import path 
from alok_tracker.views import *

urlpatterns = [
    path("users/", users_display, name="users"),
    path("create_user/", user_create, name="create_user"),
    path("delete_user/", user_delete, name="delete_user"),
    path("update_user/", user_update, name="update_user"),
    path("upload_file/", upload_tracker_data_view, name="upload_tracker_data"),
    path("download_tracker_file/", download_tracker_data_view, name="download_tracker_data"),
    path("daily_dashboard_file/", daily_dashboard_view, name="daily_dashboard"),
    path("weekly_monthly_dashboard_file/", weekly_monthly_dashboard_view, name="weekly_mpnthly_dashboard"),
    path("gap_view/", gap_view, name="GAP"),
    path("ageing_dashboard_file/", ageing_dashboard_view, name="ageing_dashboard"),
    path("ageing_dashboard_issues/", ageing_dashboard_view_issues, name="ageing_issues"),
    path("hyperlink_frontend_editing/", frontend_editing_display_view, name="hyperlink_frontend_editing"),
    path("hyperlink_frontend_editing_update/", frontend_editing_update_view, name="hyperlink_frontend_editing_update"),
    path("graphs/", graphs_view, name="graphs"),
    path("ms2_daily_dashboard/", ms2_daily_waterfall, name="ms2_daily_dashboard"),
    path("ms2_weekly_monthly_dashboard/", ms2_weekly_monthly_waterfall, name="ms2_weekly_monthly_dashboard"),
    path("monthly_graph/", monthly_graph, name="monthly_graph"),
    path("lifecycle_display/", lifecycle_display, name="lifecycle_display"),
    path("issue_timeline_display/", issue_timeline_display, name="issue_timeline"),
    path("issue_timeline_add/", issue_timeline_add, name="issue_timeline_add"),
    path("issue_timeline_update/", issue_timeline_update, name="issue_timeline_update"),
    path("issue_timeline_delete/", issue_timeline_delete, name="issue_timeline_delete"),
    path("delete_dropped/", delete_dropped_sites, name = "delete dropped"),
    path("delete_specific/", delete_specific_site, name = "delete specific"),
    path("upload_dump/", upload_ftr_dump, name = "upload_dump"),
    path("ftr_table/", ftr_table, name="ftr_table"),
    path("ftr_table_circlewise/", ftr_table_circlewise, name="ftr_table_circlewise"),
    path("upload_site_status/", upload_site_status_table, name="upload_site_status"),
    path("delete_site_status/", delete_dropped_sites_status, name="dlete_site_status"),
    path("sync_status/", sync_alok_tracker_to_site_status, name="sync_status"),
    path("dismantle_daily_dashboard/", dismantle_daily_dashboard_view, name="dismantle_daily_dashboard"),
    path("dismantle_weekly_monthly_dashboard/", dismantle_weekly_monthly_dashboard_view, name="dismantle_weekly_monthly_dashboard"),
    path("ms2_ageing_dashboard_table1/", ms2_ageing_dashboard_table1, name="ms2_ageing_dashboard_table1"),
    path("ms2_ageing_dashboard_table2/", ms2_ageing_dashboard_table2, name="ms2_ageing_dashboard_table2"),
    path("ms2_graphs/", ms2_graphs_view, name="graphs"),
    path("ms2_monthly_graph/", ms2_monthly_graph, name="monthly_graph"),
    path("dismantle_ageing_dashboard_table1/", dismantle_ageing_dashboard_table1, name="dismantle_ageing_dashboard_table1"),
    path("dismantle_ageing_dashboard_table2/", dismantle_ageing_dashboard_table2, name="dismantle_ageing_dashboard_table2"),
    path("dismantle_graphs/", dismantle_graphs_view, name="graphs"),
    path("dismantle_monthly_graph/", dismantle_monthly_graph, name="monthly_graph"),
    path("upload_issues_data_view/", upload_issues_data_view, name="upload_issues_data_view"),
    path("fetch_sites/", fetch_sites, name="fetch_sites"),
]