print("DailyTaskReview tasks loaded")
from django.test import TestCase

import os
import requests
import zipfile
import py7zr
import shutil
from datetime import datetime
from celery import shared_task
from mcom_website.settings import MEDIA_ROOT
from mailapp.tasks import send_email
import pandas as pd  # make sure this is your Celery email task
from jinja2 import Environment, FileSystemLoader
from datetime import datetime
import os
from premailer import transform
from universal_alarm.models import OldvsNew
from django.utils import timezone
from datetime import datetime
from mailapp.tasks import send_email
import imaplib
import email
import io
import smtplib
from email.mime.text import MIMEText
from email.header import decode_header
from email.utils import parseaddr
from DailyTaskReview.models import Dailytaskreviewmodel
from datetime import datetime




EMAIL       = "noreply@mcpspmis.com"
PASSWORD    = "Mcom@#2027"
IMAP_SERVER = "imap.secureserver.net"
IMAP_PORT   = 993


def format_datetime(value):

    if not value:
        return ""

    # Already datetime object
    if isinstance(value, datetime):
        return value.strftime("%d-%m-%Y %I:%M %p")

    # ISO string
    if isinstance(value, str):
        return datetime.fromisoformat(value).strftime(
            "%d-%m-%Y %I:%M %p"
        )

    return str(value)

def send_email_updateTask(task_Data):

    status_color = "#28a745" if task_Data["status"] == "Completed" else "#ffc107"

    body = f"""
    <html>
    <body style="font-family:Arial, sans-serif;background-color:#f5f5f5;">

    <div style="max-width:750px;margin:auto;background:white;padding:30px;border-radius:10px;">

        <h2 style="color:#1f4e79;">
            🔔 Task Status Updated
        </h2>

        <p>Hello,</p>

        <p>
            The assigned user has updated the status of the following task.
        </p>

        <table style="width:100%;border-collapse:collapse;">

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Ticket No.</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['task_id']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>OEM</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['oem']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Task</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['task']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Updated By</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data.get('updated_by', 'N/A')}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Current Status</b></td>
                <td style="padding:10px;border:1px solid #ddd;color:{status_color};">
                    <b>{task_Data['status']}</b>
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Priority</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['priority']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Frequency</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['frequency']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Deadline</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {format_datetime(task_Data['deadline'])}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Remarks</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['remarks']}
                </td>
            </tr>

        </table>

        <br>

        <div style="
            background-color:#f8f9fa;
            padding:15px;
            border-left:5px solid {status_color};
        ">

            <b>Status Update:</b><br><br>

            User <b>{task_Data.get('updated_by', 'N/A')}</b>
            has marked the task
            <b>{task_Data['task']}</b>
            as
            <b>{task_Data['status']}</b>.

        </div>

        <br>

        <hr>

        <p style="font-size:12px;color:gray;">
            This is an automated notification generated by Daily Task Review System.
        </p>

    </div>

    </body>
    </html>
    """

    if task_Data["status"] == "Completed":
        subject = f"✅ Task Completed | {task_Data['task_id']}"
    else:
        subject = f"🔔 Task Updated | {task_Data['task_id']}"

    # Mail goes to the assigner
    to_mail = task_Data["assigned_by"]

    # CC all owners
    # cc_mail = ";".join(task_Data["owner"])
    cc_mail = ""

    send_email(
        to_mail,
        cc_mail,
        subject,
        body,
        None,
        True
    )


@shared_task
def check_outlook_mail():

    print("Checking mailbox...")

    try:

        mail = imaplib.IMAP4_SSL(IMAP_SERVER, IMAP_PORT)
        mail.login(EMAIL, PASSWORD)
        mail.select("INBOX")

        # Read only unread mails
        status, messages = mail.search(None, "UNSEEN")

        if status != "OK":
            print("Unable to search mailbox.")
            mail.logout()
            return

        mail_ids = messages[0].split()

        if not mail_ids:
            print("No unread mails.")
            mail.logout()
            return

        for mail_id in mail_ids:

            try:

                status, msg_data = mail.fetch(mail_id, "(RFC822)")

                if status != "OK":
                    continue

                msg = email.message_from_bytes(msg_data[0][1])

                # --------------------------------------------------
                # Subject
                # --------------------------------------------------

                decoded = decode_header(msg["Subject"])[0][0]

                if isinstance(decoded, bytes):
                    subject = decoded.decode(errors="ignore")
                else:
                    subject = str(decoded)

                subject = subject.strip()

                print(f"\nSubject : {subject}")

                if not subject.startswith("Task Update"):
                    print("Skipped (Not Task Update)")
                    mail.store(mail_id, '+FLAGS', '\\Seen')
                    continue

                # --------------------------------------------------
                # Sender
                # --------------------------------------------------

                sender = parseaddr(msg.get("From"))[1].strip().lower()

                print("Sender :", sender)

                # --------------------------------------------------
                # Parse Subject
                # Expected:
                # Task Update | DTR30062026/000100 | Completed
                # --------------------------------------------------

                parts = [x.strip() for x in subject.split("|")]

                if len(parts) != 3:
                    print("Invalid Subject Format")
                    mail.store(mail_id, '+FLAGS', '\\Seen')
                    continue

                task_id = parts[1]
                task_status = parts[2]

                print("Task ID :", task_id)
                print("Status  :", task_status)

                if task_status not in [
                    "Completed",
                    "Pending",
                    "In Progress"
                ]:
                    print("Invalid Status")
                    mail.store(mail_id, '+FLAGS', '\\Seen')
                    continue

                # --------------------------------------------------
                # Fetch Task
                # --------------------------------------------------

                task = Dailytaskreviewmodel.objects.filter(
                    task_id=task_id
                ).first()

                if not task:
                    print("Task not found")
                    mail.store(mail_id, '+FLAGS', '\\Seen')
                    continue

                owners = [
                    x.strip().lower()
                    for x in task.owner
                ]

                print("Owners :", owners)

                if sender not in owners:
                    print("Sender is not task owner")
                    mail.store(mail_id, '+FLAGS', '\\Seen')
                    continue

                # --------------------------------------------------
                # Already Updated?
                # --------------------------------------------------

                # if task.status == task_status:
                #     print("Status already updated.")
                #     mail.store(mail_id, '+FLAGS', '\\Seen')
                #     continue

                # --------------------------------------------------
                # Update Database
                # --------------------------------------------------

                task.status = task_status
                task.updated_by = sender
                task.updated_at = timezone.now()
                task.save()

                print(f"{task.task_id} updated successfully.")

                # --------------------------------------------------
                # Send Notification
                # --------------------------------------------------

                task_data = {
                    "task_id": task.task_id,
                    "oem": task.oem,
                    "task": task.task,
                    "owner": task.owner,
                    "assigned_by": task.assigned_by,
                    "status": task.status,
                    "priority": task.priority,
                    "frequency": task.frequency,
                    "deadline": task.deadline,
                    "remarks": task.remarks,
                    "updated_by": sender,
                }

                print('task data',task_data )

                send_email_updateTask(task_data)

                print("Notification sent.")

                # --------------------------------------------------
                # Mark Mail Seen
                # --------------------------------------------------

                mail.store(mail_id, '+FLAGS', '\\Seen')

            except Exception as ex:

                print("Mail Processing Error :", ex)

                try:
                    mail.store(mail_id, '+FLAGS', '\\Seen')
                except:
                    pass

        mail.logout()

    except Exception as e:

        print("Mail Reader Error :", e)

# @shared_task
# def check_outlook_mail():

#     print("Checking...")

#     try:

#         mail = imaplib.IMAP4_SSL(IMAP_SERVER, IMAP_PORT)
#         mail.login(EMAIL, PASSWORD)
#         mail.select("INBOX")

#         status, messages = mail.search(None, "UNSEEN")

#         if status != "OK":
#             print("Unable to search mailbox.")
#             mail.logout()
#             return

#         mail_ids = messages[0].split()

#         if not mail_ids:
#             print("No unread mails.")
#             mail.logout()
#             return

#         for mail_id in mail_ids:

#             status, msg_data = mail.fetch(mail_id, "(RFC822)")

#             if status != "OK":
#                 continue

#             msg = email.message_from_bytes(msg_data[0][1])

#             # ---------------- Subject ----------------

#             subject = decode_header(msg["Subject"])[0][0]

#             if isinstance(decoded, bytes):
#                 subject = decoded.decode(errors="ignore")
#             else:
#                 subject = str(decoded)

#             subject = subject.strip()

#             print(subject,"subject")

#             if not subject.startswith("Task Update"):
#                 mail.store(mail_id, '+FLAGS', '\\Seen')
#                 continue

#             # ---------------- Sender ----------------

#             # sender = parseaddr(msg.get("From"))[1]
#             sender = parseaddr(msg.get("From"))[1].strip().lower()

#             print(sender,"sender")

#             # ---------------- Parse Subject ----------------

#             try:

#                 parts = [x.strip() for x in subject.split("|")]

#                 print(parts,"parts")

#                 if len(parts) != 3:
#                     raise Exception("Invalid Subject")

#                 task_id = parts[1]
#                 task_status = parts[2]


#                 print(task_id,"task_id",task_status,"task_status")

#             except Exception as e:

#                 print(e,"error")
#                 mail.store(mail_id, '+FLAGS', '\\Seen')
#                 continue

#             if task_status not in ["Completed","Pending","In Progress"]:
#                 print("Invalid Status")
#                 mail.store(mail_id, '+FLAGS', '\\Seen')
#                 continue

#             # ---------------- Fetch Task ----------------
#             print('task ID ', task_id, 'sender', sender)

#             task = Dailytaskreviewmodel.objects.filter(task_id=task_id,owner__contains=[sender]).first()

#             if task is None:

#                 print("Task not found")

#                 mail.store(mail_id, '+FLAGS', '\\Seen')
#                 continue

#             # Already same status

#             if task.status == task_status:

#                 print("Status already updated.")

#                 mail.store(mail_id, '+FLAGS', '\\Seen')
#                 continue

#             # ---------------- Update ----------------

#             task.status = task_status
#             task.updated_by = sender
#             task.updated_at = timezone.now()
#             task.save()

#             print(f"{task.task_id} updated.")

#             # ---------------- Send Notification ----------------

#             task_data = {
#                 "task_id": task.task_id,
#                 "oem": task.oem,
#                 "task": task.task,
#                 "owner": task.owner,
#                 "assigned_by": task.assigned_by,
#                 "status": task.status,
#                 "priority": task.priority,
#                 "frequency": task.frequency,
#                 "deadline": task.deadline,
#                 "remarks": task.remarks,
#                 "updated_by": sender,
#             }

#             send_email_updateTask(task_data)

#             print("Notification sent.")

#             # ---------------- Mark Seen ----------------

#             mail.store(mail_id, '+FLAGS', '\\Seen')

#         mail.logout()

#     except Exception as e:

#         print("Mail Reader Error :", e)



