from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .models import *
from .serializers import *
from django.contrib.auth.models import User
from mailapp.tasks import send_email


def SplitFirstNameFromEmail(email_list):
    names = []
    for email in email_list:
       names.append(email.split('@')[0].split('.')[0])
    return ",".join(names)

def send_email_assignTask(task_Data):

    body = f"""
    <html>
    <body style="font-family:Arial, sans-serif;background-color:#f5f5f5;">

    <div style="max-width:750px;margin:auto;background:white;padding:30px;border-radius:10px;">

        <h2 style="color:#1f4e79;">
            📌 New Task Assigned
        </h2>

        <p>Hi {SplitFirstNameFromEmail([task_Data['owner']])},</p>

        <p>
            You have been assigned a new task by
            <b>{task_Data['assigned_by']}</b>.
            Please review the task details below.
        </p>

        <table style="width:100%;border-collapse:collapse;">

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Ticket No.</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['task_id']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>OEM</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['oem']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Task</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['task']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Priority</b></td>
                <td style="padding:10px;border:1px solid #ddd;color:red;">
                    <b>{task_Data['priority']}</b>
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Status</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['status']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Slot</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['slot']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Frequency</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['frequency']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Assigned At</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['assigned_at']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Deadline</b></td>
                <td style="padding:10px;border:1px solid #ddd; color:red;">
                    <b>
                    {task_Data['deadline']}
                    </b>
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Remarks</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['remarks']}
                </td>
            </tr>

        </table>

        <br>

        <div style="text-align:center;">

            <a href="https://yourfrontend.com/task-action?task_id={task_Data['task_id']}&status=Completed"
               style="
                    background:#28a745;
                    color:white;
                    padding:15px 30px;
                    text-decoration:none;
                    border-radius:5px;
                    font-weight:bold;
                    margin-right:20px;">
                ✅ Completed
            </a>

            <a href="https://yourfrontend.com/task-action?task_id={task_Data['task_id']}&status=Pending"
               style="
                    background:#dc3545;
                    color:white;
                    padding:15px 30px;
                    text-decoration:none;
                    border-radius:5px;
                    font-weight:bold;">
                ⏳ Pending
            </a>

        </div>

        <br>

        <p>
            Please update the task status accordingly.
        </p>

        <hr>

        <p style="font-size:12px;color:gray;">
            This is an automated email generated by Daily Task Review System.
        </p>

    </div>

    </body>
    </html>
    """

    subject = f"New Task Assigned | {task_Data['task_id']}"

    to_mail = task_Data["owner"]
    to_mail = ";".join(to_mail)


    # cc_mail = task_Data["assigned_by"]


    send_email(
        to_mail,
        # cc_mail,
        subject,
        body,
        None,
        True
    )

def send_email_updateTask(task_Data):

    status_color = "#28a745" if task_Data["status"] == "Completed" else "#ffc107"

    body = f"""
    <html>
    <body style="font-family:Arial, sans-serif;background-color:#f5f5f5;">

    <div style="max-width:750px;margin:auto;background:white;padding:30px;border-radius:10px;">

        <h2 style="color:#1f4e79;">
            🔔 Task Status Updated
        </h2>

        <p>Hello,</p>

        <p>
            The assigned user has updated the status of the following task.
        </p>

        <table style="width:100%;border-collapse:collapse;">

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Ticket No.</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['task_id']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>OEM</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['oem']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Task</b></td>
                <td style="padding:10px;border:1px solid #ddd;">{task_Data['task']}</td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Updated By</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data.get('updated_by', 'N/A')}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Current Status</b></td>
                <td style="padding:10px;border:1px solid #ddd;color:{status_color};">
                    <b>{task_Data['status']}</b>
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Priority</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['priority']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Frequency</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['frequency']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Deadline</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['deadline']}
                </td>
            </tr>

            <tr>
                <td style="padding:10px;border:1px solid #ddd;"><b>Remarks</b></td>
                <td style="padding:10px;border:1px solid #ddd;">
                    {task_Data['remarks']}
                </td>
            </tr>

        </table>

        <br>

        <div style="
            background-color:#f8f9fa;
            padding:15px;
            border-left:5px solid {status_color};
        ">

            <b>Status Update:</b><br><br>

            User <b>{task_Data.get('updated_by', 'N/A')}</b>
            has marked the task
            <b>{task_Data['task']}</b>
            as
            <b>{task_Data['status']}</b>.

        </div>

        <br>

        <hr>

        <p style="font-size:12px;color:gray;">
            This is an automated notification generated by Daily Task Review System.
        </p>

    </div>

    </body>
    </html>
    """

    if task_Data["status"] == "Completed":
        subject = f"✅ Task Completed | {task_Data['task_id']}"
    else:
        subject = f"🔔 Task Updated | {task_Data['task_id']}"

    # Mail goes to the assigner
    to_mail = task_Data["assigned_by"]

    # CC all owners
    cc_mail = ";".join(task_Data["owner"])

    send_email(
        to_mail,
        cc_mail,
        subject,
        body,
        None,
        True
    )


# ======= Add Task Table CRUD =======


@api_view(['POST'])
def add_task_to_table(request):
    serializer = AddTaskTableSerializer(data=request.data)

    if serializer.is_valid():
        serializer.save()
        return Response(
            {
                "message": "Task added successfully",
                "data": serializer.data
            },
            status=status.HTTP_201_CREATED
        )
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','POST'])
def get_tasks_from_table(request):
    tasks = AddTaskTable.objects.filter(userID=request.data.get('userID'))
    serializer = AddTaskTableSerializer(tasks, many=True)

    return Response(
        {
            "message": "Tasks fetched successfully",
            "data": serializer.data
        },
        status=status.HTTP_200_OK
    )

@api_view(['PUT'])
def update_task_in_table(request, pk):
    try:
        task = AddTaskTable.objects.get(id=pk)
    except AddTaskTable.DoesNotExist:
        return Response(
            {"error": "Task not found"},
            status=status.HTTP_404_NOT_FOUND
        )

    serializer = AddTaskTableSerializer(task, data=request.data)

    if serializer.is_valid():
        serializer.save()
        return Response(
            {
                "message": "Task updated successfully",
                "data": serializer.data
            },
            status=status.HTTP_200_OK
        )

    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['DELETE'])
def delete_task_from_table(request, pk):
    try:
        task = AddTaskTable.objects.get(id=pk)
    except AddTaskTable.DoesNotExist:
        return Response(
            {"error": "Task not found"},
            status=status.HTTP_404_NOT_FOUND
        )

    task.delete()

    return Response(
        {
            "message": "Task deleted successfully"
        },
        status=status.HTTP_200_OK
    )

# ================= Assign Task API function  =================



@api_view(['POST'])
def create_task(request):
    data = request.data.copy()
    data['task_type'] = 'assign'
    serializer = DailytaskreviewmodelSerializer(data=data)
    if serializer.is_valid():
        serializer.save()
        send_email_assignTask(serializer.data)
        return Response(serializer.data, status=201)
    return Response(serializer.errors, status=400)


@api_view(['POST'])
def get_all_tasks(request):

    assigned_by = request.data.get('assigned_by')
    assigned_at = request.data.get('assigned_at')

    queryset = Dailytaskreviewmodel.objects.filter(
        task_type='assign',
        assigned_by=assigned_by,
        assigned_at__date=assigned_at
    )

    serializer = DailytaskreviewmodelSerializer(queryset, many=True)

    return Response(serializer.data)


@api_view(['PUT','POST'])
def update_task(request, pk):
    try:
        task = Dailytaskreviewmodel.objects.get(id=pk)
    except Dailytaskreviewmodel.DoesNotExist:
        return Response({"error": "Task not found"}, status=404)

    serializer = DailytaskreviewmodelSerializer(
        task,
        data=request.data,
        partial=True
    )

    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=200)

    return Response(serializer.errors, status=400)


@api_view(['DELETE'])
def delete_task(request, pk):
    try:
        task = Dailytaskreviewmodel.objects.get(id=pk)
    except Dailytaskreviewmodel.DoesNotExist:
        return Response({"error": "Task not found"}, status=404)

    task.delete()

    return Response(
        {"message": "Task deleted successfully"},
        status=200
    )



#  ==== ================= My Task API function  =================

@api_view(['POST'])
def get_my_tasks(request):
    owner = request.data.get('owner')
    assigned_at = request.data.get('assigned_at')
    queryset = Dailytaskreviewmodel.objects.filter(
        # task_type='received',
        assigned_at__date=assigned_at,
    )

    if owner:
        queryset = queryset.filter(owner__contains=[owner])

    serializer = DailytaskreviewmodelSerializer(queryset, many=True)
    return Response(serializer.data, status=200)


@api_view(['PUT', 'POST'])
def update_my_task(request, pk):
    try:
        task = Dailytaskreviewmodel.objects.get(
            id=pk,
            # task_type='received'
        )
    except Dailytaskreviewmodel.DoesNotExist:
        return Response(
            {"error": "Task not found"},
            status=404
        )
    if task.status == "Completed":
        return Response(
            {
                "error": "Task is already completed and cannot be modified."
            },
            status=400
        )
    serializer = DailytaskreviewmodelSerializer(
        task,
        data=request.data,
        partial=True
    )
    if serializer.is_valid():
        serializer.save()
        send_email_updateTask(serializer.data)
        return Response(
            serializer.data,
            status=200
        )
    return Response(
        serializer.errors,
        status=400
    )

# ====== get user email and name ======
@api_view(['POST'])
def get_user_email_and_name(request):
    user_id = request.data.get('user_id')

    try:
        user = User.objects.get(id=user_id)
        return Response({
            "email": user.email,
            "name": user.get_full_name() or user.username
        }, status=200)
    except User.DoesNotExist:
        return Response({"error": "User not found"}, status=404)
