# Generated by Django 4.1.3 on 2024-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RCA_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI', models.CharField(max_length=500)),
                ('Probable_causes', models.CharField(max_length=500)),
                ('Data_source', models.CharField(max_length=500)),
                ('Tentative_counters', models.CharField(max_length=500)),
                ('Condition_check', models.IntegerField()),
                ('Operator', models.CharField(max_length=100)),
                ('RCA', models.CharField(max_length=500)),
                ('Proposed_solution', models.CharField(max_length=500)),
                ('TT_to_be_raised_to', models.CharField(max_length=500)),
            ],
        ),
    ]
