# Generated by Django 4.1.3 on 2024-05-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rca_table',
            name='Condition_check',
            field=models.FloatField(),
        ),
    ]
