# Generated by Django 4.1.3 on 2024-05-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0002_alter_rca_table_condition_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rca_table',
            name='TT_to_be_raised_to',
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Data_source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='KPI',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Operator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Probable_causes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Proposed_solution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='RCA',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Tentative_counters',
            field=models.CharField(max_length=255),
        ),
    ]
