# Generated by Django 4.1.3 on 2024-05-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0003_remove_rca_table_tt_to_be_raised_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rca_table',
            name='Condition_check',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='KPI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Probable_causes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Proposed_solution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='RCA',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rca_table',
            name='Tentative_counters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
