# Generated by Django 4.1.3 on 2024-06-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0004_alter_rca_table_condition_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI', models.CharField(max_length=500)),
                ('threshold_value', models.FloatField()),
            ],
        ),
    ]
