# Generated by Django 4.1.3 on 2024-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0006_daily_4g_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi_table',
            name='operator',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
