# Generated by Django 4.1.3 on 2024-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0007_kpi_table_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='RRC_Max_User_Fails',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='UL_DL_BLER',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
