# Generated by Django 4.1.3 on 2024-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0008_daily_4g_kpi_rrc_max_user_fails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='ERAB_NBR_DL_FAIL_OVL_AVG',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='ERAB_NBR_UL_FAIL_OVL_AVG',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
