# Generated by Django 4.1.3 on 2024-06-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0009_daily_4g_kpi_erab_nbr_dl_fail_ovl_avg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationId', models.CharField(db_index=True, max_length=255, unique=True)),
                ('AlarmNumber', models.CharField(max_length=255)),
                ('AlarmType', models.CharField(max_length=255)),
                ('Severity', models.CharField(max_length=50)),
                ('AlarmTime', models.DateTimeField()),
                ('ProbableCause', models.TextField()),
                ('ProbableCauseCode', models.CharField(max_length=255)),
                ('AlarmText', models.TextField()),
                ('DistinguishedName', models.CharField(max_length=255)),
                ('ObjectClass', models.CharField(max_length=255)),
                ('AcknowledgementState', models.CharField(max_length=50)),
                ('AcknowledgementTimeOrUnacknowledgementTime', models.DateTimeField()),
                ('AcknowledgementUser', models.CharField(blank=True, max_length=255, null=True)),
                ('CancelState', models.CharField(max_length=50)),
                ('CancelTime', models.DateTimeField(blank=True, null=True)),
                ('CancelUser', models.CharField(blank=True, max_length=255, null=True)),
                ('Name', models.CharField(max_length=255)),
                ('MaintenanceRegionName', models.CharField(max_length=255)),
                ('SiteName', models.CharField(max_length=255)),
                ('SitePriority', models.CharField(max_length=50)),
                ('SiteAddress', models.TextField()),
                ('ExtraInformation', models.TextField(blank=True, null=True)),
                ('DiagnosticInfo', models.TextField(blank=True, null=True)),
                ('UserAdditionalInformation', models.TextField(blank=True, null=True)),
                ('SupplementaryInformation', models.TextField(blank=True, null=True)),
                ('AdditionalInformation1', models.TextField(blank=True, null=True)),
                ('AdditionalInformation2', models.TextField(blank=True, null=True)),
                ('AdditionalInformation3', models.TextField(blank=True, null=True)),
                ('CorrelationIndicator', models.CharField(max_length=50)),
                ('NotesIndicator', models.CharField(max_length=50)),
                ('TroubleTicketIndicator', models.CharField(max_length=50)),
                ('AlarmSound', models.CharField(max_length=50)),
                ('InstanceCounter', models.IntegerField()),
                ('ConsecutiveNumber', models.IntegerField()),
                ('AlarmInsertionTime', models.DateTimeField()),
                ('AlarmUpdateTime', models.DateTimeField(blank=True, null=True)),
                ('ControllingObjectName', models.CharField(max_length=255)),
                ('OriginAlarmTime', models.DateTimeField()),
                ('OriginAlarmUpdateTime', models.DateTimeField(blank=True, null=True)),
                ('OriginAcknowledgementOrUnacknowledgementTime', models.DateTimeField(blank=True, null=True)),
                ('OriginCancelTime', models.DateTimeField(blank=True, null=True)),
                ('RelatedDns', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alarm Notification',
                'verbose_name_plural': 'Alarm Notifications',
                'ordering': ['-AlarmTime'],
            },
        ),
        migrations.AddIndex(
            model_name='alarmnotification',
            index=models.Index(fields=['NotificationId'], name='RCA_TOOL_al_Notific_6e0ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmnotification',
            index=models.Index(fields=['AlarmTime'], name='RCA_TOOL_al_AlarmTi_79becb_idx'),
        ),
        migrations.AddIndex(
            model_name='alarmnotification',
            index=models.Index(fields=['SiteName'], name='RCA_TOOL_al_SiteNam_f7108e_idx'),
        ),
    ]
