# Generated by Django 4.1.3 on 2024-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0010_alarmnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnotification',
            name='AcknowledgementState',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='AcknowledgementTimeOrUnacknowledgementTime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='AlarmInsertionTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='AlarmSound',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='AlarmUpdateTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='CancelState',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='CancelTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='CorrelationIndicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='NotesIndicator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='OriginAcknowledgementOrUnacknowledgementTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='OriginAlarmTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='OriginAlarmUpdateTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='OriginCancelTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
