# Generated by Django 4.1.3 on 2024-06-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0011_alter_alarmnotification_acknowledgementstate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alarmnotification',
            name='RCA_TOOL_al_Notific_6e0ec8_idx',
        ),
        migrations.RemoveIndex(
            model_name='alarmnotification',
            name='RCA_TOOL_al_AlarmTi_79becb_idx',
        ),
        migrations.RemoveIndex(
            model_name='alarmnotification',
            name='RCA_TOOL_al_SiteNam_f7108e_idx',
        ),
    ]
