# Generated by Django 4.1.3 on 2024-06-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0012_remove_alarmnotification_rca_tool_al_notific_6e0ec8_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmnotification',
            options={},
        ),
    ]
