# Generated by Django 4.1.3 on 2024-06-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0013_alter_alarmnotification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnotification',
            name='AcknowledgementState',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='AlarmSound',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='NotesIndicator',
            field=models.CharField(max_length=50),
        ),
    ]
