# Generated by Django 4.1.3 on 2024-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0014_alter_alarmnotification_acknowledgementstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnotification',
            name='CancelState',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alarmnotification',
            name='CorrelationIndicator',
            field=models.CharField(max_length=50),
        ),
    ]
