# Generated by Django 4.1.3 on 2024-06-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0015_alter_alarmnotification_cancelstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmnotification',
            name='NotificationId',
            field=models.CharField(max_length=255),
        ),
    ]
