# Generated by Django 4.1.3 on 2024-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0017_tantitive_counters_24_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tantitive_counters_24_hours',
            options={'verbose_name': 'Tentative Counter', 'verbose_name_plural': 'Tentative Counters'},
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEARER_REL_REQ_DETACH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEARER_REL_REQ_NORM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEARER_REL_REQ_OTH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEARER_REL_REQ_RNL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEAR_REL_REQ_D_QCI1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEAR_REL_REQ_N_QCI1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEAR_REL_REQ_O_QCI1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEAR_REL_REQ_O_QCI2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEAR_REL_REQ_R_QCI1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_EPC_EPS_BEAR_REL_REQ_R_QCI2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_NBR_DL_FAIL_OVL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_NBR_UL_FAIL_OVL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_REL_ALL_ABNORMAL_H_PWR_UE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_REL_DOUBLE_S1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_REL_DOUBLE_S1_QCI1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LRRC_DISC_RRC_PAGING',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LRRC_REJ_RRC_CONN_RE_ESTAB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LRRC_RRC_CON_RE_ESTAB_ATT_HO_FAIL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LRRC_RRC_CON_RE_ESTAB_ATT_OTHER',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LRRC_RRC_PAGING_REQUESTS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LS1AP_S1AP_KILL_REQ',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LS1AP_S1AP_KILL_RESP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LS1AP_S1AP_PARTIAL_RESET_INIT_MME',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LXPL_SCG_ADD_COMPLETION_FAIL_T',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LXPL_SCG_MOD_ADD_MENB_COMPL_FAIL_T',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LXPL_SGNB_ADD_COMPL_FAIL_T',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='MME_Generated_Issues_on_Cells',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='MV_ERAB_Setup_Success_Rate_CDBH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='MV_RRC_Setup_Success_Rate_CDBH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='MV_Radio_NW_Availability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='NX2CC_NX2CC_RAB_REL_ABNORM_SGNB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='NX2CC_NX2CC_RAB_REL_ATT_MENB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='NX2CC_NX2CC_RAB_REL_ATT_SGNB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='NX2CC_NX2CC_RAB_REL_NORM_MENB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='NX2CC_NX2CC_RAB_REL_PREEM_SGNB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='Nokia_S1_Failures_MME_Issue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='RRC_CONN_REL_TA_LIMIT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='RSRP_Samples_lt_116_dBm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='S1_Failure_CDBH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='S1_Failures_MME_Issue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='TNL_Failure_Count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='TNL_Failure_Percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
