# Generated by Django 4.1.3 on 2024-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0018_alter_tantitive_counters_24_hours_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_4g_kpi',
            name='MV_eCell_Data_BH',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
