# Generated by Django 4.1.3 on 2024-06-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0019_alter_daily_4g_kpi_mv_ecell_data_bh'),
    ]

    operations = [
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='UL_RSSI',
            field=models.FloatField(default=0, max_length=500),
        ),
    ]
