# Generated by Django 4.1.3 on 2024-06-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0020_tantitive_counters_24_hours_ul_rssi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='UL_DL_BLER',
            field=models.FloatField(default=0, max_length=500),
        ),
    ]
