# Generated by Django 4.1.3 on 2024-06-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0021_tantitive_counters_24_hours_ul_dl_bler'),
    ]

    operations = [
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='ERAB_NBR_UL_FAIL_OVL_AVG',
            field=models.FloatField(default=0, max_length=500),
        ),
    ]
