# Generated by Django 4.1.3 on 2024-06-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0022_tantitive_counters_24_hours_erab_nbr_ul_fail_ovl_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tantitive_counters_24_hours',
            name='ERAB_NBR_UL_FAIL_OVL_AVG',
        ),
        migrations.RemoveField(
            model_name='tantitive_counters_24_hours',
            name='UL_DL_BLER',
        ),
    ]
