# Generated by Django 4.1.3 on 2024-06-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0023_remove_tantitive_counters_24_hours_erab_nbr_ul_fail_ovl_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='RRC_Max_User_Fails',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
