# Generated by Django 4.1.3 on 2024-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0024_tantitive_counters_24_hours_rrc_max_user_fails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='DL_BLER',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='UL_BLER',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tantitive_counters_24_hours',
            name='RRC_Max_User_Fails',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
