# Generated by Django 4.1.3 on 2024-06-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0025_tantitive_counters_24_hours_dl_bler_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tantitive_counters_24_hours',
            old_name='RRC_Max_User_Fails',
            new_name='MV_RRC_Failure',
        ),
    ]
