# Generated by Django 4.1.3 on 2024-06-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0026_rename_rrc_max_user_fails_tantitive_counters_24_hours_mv_rrc_failure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tantitive_counters_24_hours',
            old_name='MV_RRC_Failure',
            new_name='LUEST_SIGN_CONN_ESTAB_FAIL_MAXRRC',
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_INI_SETUP_FAIL_RNL_RIP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_INI_SETUP_FAIL_RNL_RNA',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_INI_SETUP_FAIL_RNL_UEL',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_INI_SETUP_FAIL_TNL_TRU',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LEPSB_ERAB_REL_ENB_TNL_TRU',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LUEST_SIGN_CONN_ESTAB_FAIL_PUCCH',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tantitive_counters_24_hours',
            name='LUEST_SIGN_EST_F_RRCCOMPL_MISSING',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
