# Generated by Django 4.1.3 on 2024-06-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0027_rename_mv_rrc_failure_tantitive_counters_24_hours_luest_sign_conn_estab_fail_maxrrc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tantitive_counters_24_hours',
            name='MV_ERAB_Setup_Success_Rate_CDBH',
        ),
        migrations.RemoveField(
            model_name='tantitive_counters_24_hours',
            name='MV_RRC_Setup_Success_Rate_CDBH',
        ),
    ]
