# Generated by Django 4.1.3 on 2024-06-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0028_remove_tantitive_counters_24_hours_mv_erab_setup_success_rate_cdbh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmnotification',
            name='Upload_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 19, 11, 15, 15, 327233)),
            preserve_default=False,
        ),
    ]
