# Generated by Django 4.1.3 on 2024-08-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0029_alarmnotification_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCA_output_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cell_name', models.CharField(max_length=100)),
                ('KPI', models.CharField(max_length=100)),
                ('cell_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('check_condition', models.CharField(max_length=100)),
                ('RCA', models.TextField()),
                ('Proposed_Solution', models.TextField()),
                ('history_alarms', models.TextField()),
                ('circle', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
