# Generated by Django 4.1.3 on 2024-08-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0030_rca_output_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCA_payload_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KPI', models.CharField(blank=True, max_length=255, null=True)),
                ('Probable_causes', models.CharField(blank=True, max_length=255, null=True)),
                ('Data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('Tentative_counters', models.CharField(blank=True, max_length=255, null=True)),
                ('Condition_check', models.FloatField(blank=True, null=True)),
                ('Operator', models.CharField(blank=True, max_length=255, null=True)),
                ('RCA', models.CharField(blank=True, max_length=255, null=True)),
                ('Proposed_solution', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
