# Generated by Django 4.1.3 on 2024-08-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0031_rca_payload_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='RS_Power_dB',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='dlRsBoost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
