# Generated by Django 4.1.3 on 2024-12-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0032_daily_4g_kpi_rs_power_db_daily_4g_kpi_dlrsboost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rca_output_table',
            name='OEM_GGSN',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
