# Generated by Django 4.1.3 on 2024-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0033_rca_output_table_oem_ggsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='MV_CSFB_Redirection_Success_Rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='MV_RRC_Setup_Success_Rate_DENOM',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='VoLTE_Inter_Frequency_Handover_Success_Ratio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='VoLTE_Intra_LTE_Handover_Success_Ratio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
