# Generated by Django 4.1.3 on 2025-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0036_alter_daily_4g_kpi_mv_4g_data_volume_gb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_4g_kpi',
            name='MV_DL_User_Throughput_Kbps',
            field=models.FloatField(),
        ),
    ]
