# Generated by Django 5.2.1 on 2025-05-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RCA_TOOL', '0037_alter_daily_4g_kpi_mv_dl_user_throughput_kbps'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='MV_DL_User_Throughput_Kbps_CUBH',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='MV_VoLTE_Packet_Loss_DL_CBBH',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='MV_VoLTE_Packet_Loss_UL_CBBH',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='daily_4g_kpi',
            name='Sams_Average_UE_Distance_KM',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
